// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Silas Müller <github@silasmueller.de>
// SPDX-FileCopyrightText: 2026 Universität Stuttgart, IKR
//! Raw bindings to the NVIDIA SDK headers, for every driver version
//! `abi.toml` names.
//!
//! Generated by `cargo xtask abi`. Do not edit: the next run discards
//! hand work, and CI checks that a run produces no diff.
//!
//! The shape, and why it is this shape:
//!
//!   * [`stable`] holds every name that is the same on every version.
//!     It is re-exported at the crate root, so `nvrm_sys::NVOS64_PARAMETERS`
//!     means what it always meant.
//!   * one module per version holds what is not. Those names are NOT
//!     re-exported at the root, because two versions would collide there
//!     and the collision is the whole point: they are different types.
//!   * [`RmAbi`] names the ones a caller has to be generic over.
//!
//! Features are additive. Each `v<NNN>` enables a module and disables
//! nothing; all of them at once compiles, and with exactly one enabled
//! the dispatch in [`DriverVersion`] has a single arm.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(dead_code, clippy::all)]

/// Asserts a measured layout: the size, the alignment and one offset
/// per field, all of them read from `manifests/<version>.json`.
///
/// This is what keeps the committed source and the committed evidence
/// together. Breaking it means one of the two moved without the other.
macro_rules! assert_layout {
    ($t:ty, size = $size:expr, align = $align:expr $(, $field:ident @ $off:expr)* $(,)?) => {
        const _: () = {
            assert!(::core::mem::size_of::<$t>() == $size);
            assert!(::core::mem::align_of::<$t>() == $align);
            $( assert!(::core::mem::offset_of!($t, $field) == $off); )*
        };
    };
}

mod version;
pub use version::{assert_driver_version, detect, running_driver_version};

pub mod stable;
pub use stable::*;

#[cfg(feature = "v580")]
pub mod v580;
#[cfg(feature = "v595")]
pub mod v595;
#[cfg(feature = "v610")]
pub mod v610;
#[cfg(feature = "v615")]
pub mod v615;

/// The driver version this crate defaults to: the one in `DRIVER_VERSION`
/// at the repository root, and the one the `default` feature enables.
pub const DRIVER_VERSION: &str = "610.57.04";

/// Every driver version this crate carries a layout for, oldest first.
pub const SUPPORTED_VERSIONS: &[&str] = &["580.178.04", "595.99.02", "610.57.04", "615.71.09"];

/// Which supported driver a running system has.
///
/// Guest and host driver versions are assumed equal, so this is read
/// once, on the host, and carried.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum DriverVersion {
    /// 580.178.04
    #[cfg(feature = "v580")]
    V580,
    /// 595.99.02
    #[cfg(feature = "v595")]
    V595,
    /// 610.57.04
    #[cfg(feature = "v610")]
    V610,
    /// 615.71.09
    #[cfg(feature = "v615")]
    V615,
}

impl DriverVersion {
    /// The version string as `/proc/driver/nvidia/version` spells it.
    pub fn as_str(self) -> &'static str {
        match self {
            #[cfg(feature = "v580")]
            DriverVersion::V580 => "580.178.04",
            #[cfg(feature = "v595")]
            DriverVersion::V595 => "595.99.02",
            #[cfg(feature = "v610")]
            DriverVersion::V610 => "610.57.04",
            #[cfg(feature = "v615")]
            DriverVersion::V615 => "615.71.09",
        }
    }

    /// The supported version this string names, or `None`.
    ///
    /// A version that is not here is REFUSED rather than approximated.
    /// A minor release joins a branch by having the same manifest, which
    /// gives it its own entry in `abi.toml`; a version with no entry has
    /// not been measured, and guessing which layout it takes is the one
    /// mistake this whole crate exists to prevent.
    pub fn from_version_string(s: &str) -> Option<Self> {
        match s {
            #[cfg(feature = "v580")]
            "580.178.04" => Some(DriverVersion::V580),
            #[cfg(feature = "v595")]
            "595.99.02" => Some(DriverVersion::V595),
            #[cfg(feature = "v610")]
            "610.57.04" => Some(DriverVersion::V610),
            #[cfg(feature = "v615")]
            "615.71.09" => Some(DriverVersion::V615),
            _ => None,
        }
    }
}

/// The MODULE of [`DRIVER_VERSION`].
///
/// For the handful of names that cannot go through [`RmAbi`] at all
/// because some supported version does not have them -- the NVA083
/// virtual-display constants, which arrive with R595. Reaching for
/// this is a statement that the code only works on drivers that have
/// the name, and the compiler cannot check that for you.
#[cfg(feature = "v610")]
pub use v610 as default_version;

/// The ABI of [`DRIVER_VERSION`].
///
/// For code that is deliberately single-version -- a test, a
/// diagnostic, a tool that only ever runs beside the driver this
/// build was made for. Anything that has to work on more than one
/// takes `A: RmAbi` and gets it from [`dispatch`].
#[cfg(feature = "v610")]
pub type DefaultAbi = V610;

/// The types whose layout depends on the driver version, and the sizes
/// that go on the wire with them.
///
/// The set is DERIVED: it is exactly the mediated types in `abi.toml`
/// that are not identical on every supported version. A type that does
/// not move is not here -- it lives in [`stable`] and is used directly.
///
/// There is no trait hierarchy between versions and there is no shared
/// supertype. Two versions that agree about a type share it by
/// re-export, never by inheritance.
///
/// `Copy + 'static` because an implementation is a marker type with no
/// data: it exists to be a type parameter, is never held, and must not
/// drag a lifetime into everything generic over it.
pub trait RmAbi: Copy + 'static {
    /// Which driver this implementation is the ABI of.
    const VERSION: DriverVersion;

    /// `NV_CHANNEL_ALLOC_PARAMS`, as this driver version lays it out.
    type AllocChannelParams: Copy;
    /// `size_of::<Self::AllocChannelParams>()`, for the `paramsSize` a call carries.
    const ALLOC_CHANNEL_PARAMS_SIZE: u32;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, hObjectError)`.
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectError: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, hObjectBuffer)`.
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectBuffer: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, gpFifoOffset)`.
    const ALLOC_CHANNEL_PARAMS_OFF_gpFifoOffset: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, gpFifoEntries)`.
    const ALLOC_CHANNEL_PARAMS_OFF_gpFifoEntries: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, flags)`.
    const ALLOC_CHANNEL_PARAMS_OFF_flags: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, hContextShare)`.
    const ALLOC_CHANNEL_PARAMS_OFF_hContextShare: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, hVASpace)`.
    const ALLOC_CHANNEL_PARAMS_OFF_hVASpace: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, hUserdMemory)`.
    const ALLOC_CHANNEL_PARAMS_OFF_hUserdMemory: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, userdOffset)`.
    const ALLOC_CHANNEL_PARAMS_OFF_userdOffset: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, engineType)`.
    const ALLOC_CHANNEL_PARAMS_OFF_engineType: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, cid)`.
    const ALLOC_CHANNEL_PARAMS_OFF_cid: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, subDeviceId)`.
    const ALLOC_CHANNEL_PARAMS_OFF_subDeviceId: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, hObjectEccError)`.
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectEccError: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, instanceMem)`.
    const ALLOC_CHANNEL_PARAMS_OFF_instanceMem: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, userdMem)`.
    const ALLOC_CHANNEL_PARAMS_OFF_userdMem: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, ramfcMem)`.
    const ALLOC_CHANNEL_PARAMS_OFF_ramfcMem: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, mthdbufMem)`.
    const ALLOC_CHANNEL_PARAMS_OFF_mthdbufMem: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, hPhysChannelGroup)`.
    const ALLOC_CHANNEL_PARAMS_OFF_hPhysChannelGroup: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, internalFlags)`.
    const ALLOC_CHANNEL_PARAMS_OFF_internalFlags: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, errorNotifierMem)`.
    const ALLOC_CHANNEL_PARAMS_OFF_errorNotifierMem: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, eccErrorNotifierMem)`.
    const ALLOC_CHANNEL_PARAMS_OFF_eccErrorNotifierMem: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, ProcessID)`.
    const ALLOC_CHANNEL_PARAMS_OFF_ProcessID: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, SubProcessID)`.
    const ALLOC_CHANNEL_PARAMS_OFF_SubProcessID: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, encryptIv)`.
    const ALLOC_CHANNEL_PARAMS_OFF_encryptIv: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, decryptIv)`.
    const ALLOC_CHANNEL_PARAMS_OFF_decryptIv: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, hmacNonce)`.
    const ALLOC_CHANNEL_PARAMS_OFF_hmacNonce: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, tpcConfigID)`.
    const ALLOC_CHANNEL_PARAMS_OFF_tpcConfigID: usize;
    /// `offset_of!(NV_CHANNEL_ALLOC_PARAMS, hHandleVASpace)`.
    const ALLOC_CHANNEL_PARAMS_OFF_hHandleVASpace: usize;

    /// `NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1`, as this driver version lays it out.
    type GpuNameStringBuffer: Copy;
    /// `size_of::<Self::GpuNameStringBuffer>()`, for the `paramsSize` a call carries.
    const GPU_NAME_STRING_BUFFER_SIZE: u32;
    /// `offset_of!(NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1, ascii)`.
    const GPU_NAME_STRING_BUFFER_OFF_ascii: usize;
    /// `offset_of!(NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1, unicode)`.
    const GPU_NAME_STRING_BUFFER_OFF_unicode: usize;

    /// `NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS`, as this driver version lays it out.
    type GpuNameStringParams: Copy;
    /// `size_of::<Self::GpuNameStringParams>()`, for the `paramsSize` a call carries.
    const GPU_NAME_STRING_PARAMS_SIZE: u32;
    /// `offset_of!(NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS, gpuNameStringFlags)`.
    const GPU_NAME_STRING_PARAMS_OFF_gpuNameStringFlags: usize;
    /// `offset_of!(NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS, gpuNameString)`.
    const GPU_NAME_STRING_PARAMS_OFF_gpuNameString: usize;

    /// `NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS`, as this driver version lays it out.
    type P2pCapsMatrixParams: Copy;
    /// `size_of::<Self::P2pCapsMatrixParams>()`, for the `paramsSize` a call carries.
    const P2P_CAPS_MATRIX_PARAMS_SIZE: u32;
    /// `offset_of!(NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS, grpACount)`.
    const P2P_CAPS_MATRIX_PARAMS_OFF_grpACount: usize;
    /// `offset_of!(NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS, grpBCount)`.
    const P2P_CAPS_MATRIX_PARAMS_OFF_grpBCount: usize;
    /// `offset_of!(NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS, gpuIdGrpA)`.
    const P2P_CAPS_MATRIX_PARAMS_OFF_gpuIdGrpA: usize;
    /// `offset_of!(NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS, gpuIdGrpB)`.
    const P2P_CAPS_MATRIX_PARAMS_OFF_gpuIdGrpB: usize;
    /// `offset_of!(NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS, p2pCaps)`.
    const P2P_CAPS_MATRIX_PARAMS_OFF_p2pCaps: usize;
    /// `offset_of!(NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS, a2bOptimalReadCes)`.
    const P2P_CAPS_MATRIX_PARAMS_OFF_a2bOptimalReadCes: usize;
    /// `offset_of!(NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS, a2bOptimalWriteCes)`.
    const P2P_CAPS_MATRIX_PARAMS_OFF_a2bOptimalWriteCes: usize;
    /// `offset_of!(NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS, b2aOptimalReadCes)`.
    const P2P_CAPS_MATRIX_PARAMS_OFF_b2aOptimalReadCes: usize;
    /// `offset_of!(NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS, b2aOptimalWriteCes)`.
    const P2P_CAPS_MATRIX_PARAMS_OFF_b2aOptimalWriteCes: usize;

    /// `NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS`, as this driver version lays it out.
    type TsgParams: Copy;
    /// `size_of::<Self::TsgParams>()`, for the `paramsSize` a call carries.
    const TSG_PARAMS_SIZE: u32;
    /// `offset_of!(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, hObjectError)`.
    const TSG_PARAMS_OFF_hObjectError: usize;
    /// `offset_of!(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, hObjectEccError)`.
    const TSG_PARAMS_OFF_hObjectEccError: usize;
    /// `offset_of!(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, hVASpace)`.
    const TSG_PARAMS_OFF_hVASpace: usize;
    /// `offset_of!(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, engineType)`.
    const TSG_PARAMS_OFF_engineType: usize;
    /// `offset_of!(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, bIsCallingContextVgpuPlugin)`.
    const TSG_PARAMS_OFF_bIsCallingContextVgpuPlugin: usize;
    /// `offset_of!(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, reserved)`.
    const TSG_PARAMS_OFF_reserved: usize;
    /// `offset_of!(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, internalFlags)`.
    const TSG_PARAMS_OFF_internalFlags: usize;

    /// `UVM_FREE_PARAMS`, as this driver version lays it out.
    type UvmFreeParams: Copy;
    /// `size_of::<Self::UvmFreeParams>()`, for the `paramsSize` a call carries.
    const UVM_FREE_PARAMS_SIZE: u32;
    /// `offset_of!(UVM_FREE_PARAMS, base)`.
    const UVM_FREE_PARAMS_OFF_base: usize;
    /// `offset_of!(UVM_FREE_PARAMS, length)`.
    const UVM_FREE_PARAMS_OFF_length: usize;
    /// `offset_of!(UVM_FREE_PARAMS, rmStatus)`.
    const UVM_FREE_PARAMS_OFF_rmStatus: usize;

    /// `UVM_UNREGISTER_CHANNEL_PARAMS`, as this driver version lays it out.
    type UvmUnregisterChannelParams: Copy;
    /// `size_of::<Self::UvmUnregisterChannelParams>()`, for the `paramsSize` a call carries.
    const UVM_UNREGISTER_CHANNEL_PARAMS_SIZE: u32;
    /// `offset_of!(UVM_UNREGISTER_CHANNEL_PARAMS, gpuUuid)`.
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_gpuUuid: usize;
    /// `offset_of!(UVM_UNREGISTER_CHANNEL_PARAMS, hClient)`.
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_hClient: usize;
    /// `offset_of!(UVM_UNREGISTER_CHANNEL_PARAMS, hChannel)`.
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_hChannel: usize;
    /// `offset_of!(UVM_UNREGISTER_CHANNEL_PARAMS, rmStatus)`.
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_rmStatus: usize;

    /// `NVA083_GRID_DISPLAYLESS`, or `None` where this driver's headers do not define it.
    const CLASS_DISPLAYLESS: Option<u32>;

    /// `NVA083_CTRL_CMD_VIRTUAL_DISPLAY_GET_DEFAULT_EDID`, or `None` where this driver's headers do not define it.
    const CTRL_VD_GET_DEFAULT_EDID: Option<u32>;

    /// `NVA083_CTRL_CMD_VIRTUAL_DISPLAY_GET_MAX_PIXELS`, or `None` where this driver's headers do not define it.
    const CTRL_VD_GET_MAX_PIXELS: Option<u32>;

    /// `NVA083_CTRL_CMD_VIRTUAL_DISPLAY_GET_MAX_RESOLUTION`, or `None` where this driver's headers do not define it.
    const CTRL_VD_GET_MAX_RESOLUTION: Option<u32>;

    /// `NVA083_CTRL_CMD_VIRTUAL_DISPLAY_GET_NUM_HEADS`, or `None` where this driver's headers do not define it.
    const CTRL_VD_GET_NUM_HEADS: Option<u32>;

    /// `NVA083_CTRL_CMD_VIRTUAL_DISPLAY_IS_ACTIVE`, or `None` where this driver's headers do not define it.
    const CTRL_VD_IS_ACTIVE: Option<u32>;

    /// `NVA083_CTRL_CMD_VIRTUAL_DISPLAY_IS_CONNECTED`, or `None` where this driver's headers do not define it.
    const CTRL_VD_IS_CONNECTED: Option<u32>;
}

/// A piece of work that is generic over the ABI, so that [`dispatch`]
/// can hand it the right one.
///
/// A closure cannot do this: it would have to be generic over a type
/// parameter it does not have. A one-method trait can, and costs
/// nothing -- with a single feature enabled the match below has one arm
/// and the call is direct.
pub trait AbiVisitor {
    /// What the work produces. The same type for every version, which
    /// is what lets one match answer for all of them.
    type Out;
    fn visit<A: RmAbi>(self) -> Self::Out;
}

/// THE dispatch point. The only `match` on [`DriverVersion`] in the
/// tree, by construction: everything downstream of it is generic over
/// `A: RmAbi` and never asks again.
///
/// With one version's feature enabled this match has one arm and
/// disappears; with several it is one branch, once, at start-up.
pub fn dispatch<V: AbiVisitor>(version: DriverVersion, work: V) -> V::Out {
    match version {
        #[cfg(feature = "v580")]
        DriverVersion::V580 => work.visit::<V580>(),
        #[cfg(feature = "v595")]
        DriverVersion::V595 => work.visit::<V595>(),
        #[cfg(feature = "v610")]
        DriverVersion::V610 => work.visit::<V610>(),
        #[cfg(feature = "v615")]
        DriverVersion::V615 => work.visit::<V615>(),
    }
}

/// The ABI of driver 580.178.04. See [`RmAbi`].
#[cfg(feature = "v580")]
#[derive(Clone, Copy, Debug)]
pub struct V580;

#[cfg(feature = "v580")]
impl RmAbi for V580 {
    const VERSION: DriverVersion = DriverVersion::V580;
    type AllocChannelParams = crate::v580::NV_CHANNEL_ALLOC_PARAMS;
    const ALLOC_CHANNEL_PARAMS_SIZE: u32 = 368;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectError: usize = 0;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectBuffer: usize = 4;
    const ALLOC_CHANNEL_PARAMS_OFF_gpFifoOffset: usize = 8;
    const ALLOC_CHANNEL_PARAMS_OFF_gpFifoEntries: usize = 16;
    const ALLOC_CHANNEL_PARAMS_OFF_flags: usize = 20;
    const ALLOC_CHANNEL_PARAMS_OFF_hContextShare: usize = 24;
    const ALLOC_CHANNEL_PARAMS_OFF_hVASpace: usize = 28;
    const ALLOC_CHANNEL_PARAMS_OFF_hUserdMemory: usize = 32;
    const ALLOC_CHANNEL_PARAMS_OFF_userdOffset: usize = 64;
    const ALLOC_CHANNEL_PARAMS_OFF_engineType: usize = 128;
    const ALLOC_CHANNEL_PARAMS_OFF_cid: usize = 132;
    const ALLOC_CHANNEL_PARAMS_OFF_subDeviceId: usize = 136;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectEccError: usize = 140;
    const ALLOC_CHANNEL_PARAMS_OFF_instanceMem: usize = 144;
    const ALLOC_CHANNEL_PARAMS_OFF_userdMem: usize = 168;
    const ALLOC_CHANNEL_PARAMS_OFF_ramfcMem: usize = 192;
    const ALLOC_CHANNEL_PARAMS_OFF_mthdbufMem: usize = 216;
    const ALLOC_CHANNEL_PARAMS_OFF_hPhysChannelGroup: usize = 240;
    const ALLOC_CHANNEL_PARAMS_OFF_internalFlags: usize = 244;
    const ALLOC_CHANNEL_PARAMS_OFF_errorNotifierMem: usize = 248;
    const ALLOC_CHANNEL_PARAMS_OFF_eccErrorNotifierMem: usize = 272;
    const ALLOC_CHANNEL_PARAMS_OFF_ProcessID: usize = 296;
    const ALLOC_CHANNEL_PARAMS_OFF_SubProcessID: usize = 300;
    const ALLOC_CHANNEL_PARAMS_OFF_encryptIv: usize = 304;
    const ALLOC_CHANNEL_PARAMS_OFF_decryptIv: usize = 316;
    const ALLOC_CHANNEL_PARAMS_OFF_hmacNonce: usize = 328;
    const ALLOC_CHANNEL_PARAMS_OFF_tpcConfigID: usize = 360;
    const ALLOC_CHANNEL_PARAMS_OFF_hHandleVASpace: usize = 368;
    type GpuNameStringBuffer = crate::v580::NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1;
    const GPU_NAME_STRING_BUFFER_SIZE: u32 = 128;
    const GPU_NAME_STRING_BUFFER_OFF_ascii: usize = 0;
    const GPU_NAME_STRING_BUFFER_OFF_unicode: usize = 0;
    type GpuNameStringParams = crate::v580::NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS;
    const GPU_NAME_STRING_PARAMS_SIZE: u32 = 132;
    const GPU_NAME_STRING_PARAMS_OFF_gpuNameStringFlags: usize = 0;
    const GPU_NAME_STRING_PARAMS_OFF_gpuNameString: usize = 4;
    type P2pCapsMatrixParams = crate::v580::NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS;
    const P2P_CAPS_MATRIX_PARAMS_SIZE: u32 = 1352;
    const P2P_CAPS_MATRIX_PARAMS_OFF_grpACount: usize = 0;
    const P2P_CAPS_MATRIX_PARAMS_OFF_grpBCount: usize = 4;
    const P2P_CAPS_MATRIX_PARAMS_OFF_gpuIdGrpA: usize = 8;
    const P2P_CAPS_MATRIX_PARAMS_OFF_gpuIdGrpB: usize = 40;
    const P2P_CAPS_MATRIX_PARAMS_OFF_p2pCaps: usize = 72;
    const P2P_CAPS_MATRIX_PARAMS_OFF_a2bOptimalReadCes: usize = 328;
    const P2P_CAPS_MATRIX_PARAMS_OFF_a2bOptimalWriteCes: usize = 584;
    const P2P_CAPS_MATRIX_PARAMS_OFF_b2aOptimalReadCes: usize = 840;
    const P2P_CAPS_MATRIX_PARAMS_OFF_b2aOptimalWriteCes: usize = 1096;
    type TsgParams = crate::v580::NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS;
    const TSG_PARAMS_SIZE: u32 = 20;
    const TSG_PARAMS_OFF_hObjectError: usize = 0;
    const TSG_PARAMS_OFF_hObjectEccError: usize = 4;
    const TSG_PARAMS_OFF_hVASpace: usize = 8;
    const TSG_PARAMS_OFF_engineType: usize = 12;
    const TSG_PARAMS_OFF_bIsCallingContextVgpuPlugin: usize = 16;
    const TSG_PARAMS_OFF_reserved: usize = 20;
    const TSG_PARAMS_OFF_internalFlags: usize = 20;
    type UvmFreeParams = crate::v580::UVM_FREE_PARAMS;
    const UVM_FREE_PARAMS_SIZE: u32 = 24;
    const UVM_FREE_PARAMS_OFF_base: usize = 0;
    const UVM_FREE_PARAMS_OFF_length: usize = 8;
    const UVM_FREE_PARAMS_OFF_rmStatus: usize = 16;
    type UvmUnregisterChannelParams = crate::v580::UVM_UNREGISTER_CHANNEL_PARAMS;
    const UVM_UNREGISTER_CHANNEL_PARAMS_SIZE: u32 = 28;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_gpuUuid: usize = 0;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_hClient: usize = 16;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_hChannel: usize = 20;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_rmStatus: usize = 24;
    const CLASS_DISPLAYLESS: Option<u32> = None;
    const CTRL_VD_GET_DEFAULT_EDID: Option<u32> = None;
    const CTRL_VD_GET_MAX_PIXELS: Option<u32> = None;
    const CTRL_VD_GET_MAX_RESOLUTION: Option<u32> = None;
    const CTRL_VD_GET_NUM_HEADS: Option<u32> = None;
    const CTRL_VD_IS_ACTIVE: Option<u32> = None;
    const CTRL_VD_IS_CONNECTED: Option<u32> = None;
}

/// The ABI of driver 595.99.02. See [`RmAbi`].
#[cfg(feature = "v595")]
#[derive(Clone, Copy, Debug)]
pub struct V595;

#[cfg(feature = "v595")]
impl RmAbi for V595 {
    const VERSION: DriverVersion = DriverVersion::V595;
    type AllocChannelParams = crate::v595::NV_CHANNEL_ALLOC_PARAMS;
    const ALLOC_CHANNEL_PARAMS_SIZE: u32 = 368;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectError: usize = 0;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectBuffer: usize = 4;
    const ALLOC_CHANNEL_PARAMS_OFF_gpFifoOffset: usize = 8;
    const ALLOC_CHANNEL_PARAMS_OFF_gpFifoEntries: usize = 16;
    const ALLOC_CHANNEL_PARAMS_OFF_flags: usize = 20;
    const ALLOC_CHANNEL_PARAMS_OFF_hContextShare: usize = 24;
    const ALLOC_CHANNEL_PARAMS_OFF_hVASpace: usize = 28;
    const ALLOC_CHANNEL_PARAMS_OFF_hUserdMemory: usize = 32;
    const ALLOC_CHANNEL_PARAMS_OFF_userdOffset: usize = 64;
    const ALLOC_CHANNEL_PARAMS_OFF_engineType: usize = 128;
    const ALLOC_CHANNEL_PARAMS_OFF_cid: usize = 132;
    const ALLOC_CHANNEL_PARAMS_OFF_subDeviceId: usize = 136;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectEccError: usize = 140;
    const ALLOC_CHANNEL_PARAMS_OFF_instanceMem: usize = 144;
    const ALLOC_CHANNEL_PARAMS_OFF_userdMem: usize = 168;
    const ALLOC_CHANNEL_PARAMS_OFF_ramfcMem: usize = 192;
    const ALLOC_CHANNEL_PARAMS_OFF_mthdbufMem: usize = 216;
    const ALLOC_CHANNEL_PARAMS_OFF_hPhysChannelGroup: usize = 240;
    const ALLOC_CHANNEL_PARAMS_OFF_internalFlags: usize = 244;
    const ALLOC_CHANNEL_PARAMS_OFF_errorNotifierMem: usize = 248;
    const ALLOC_CHANNEL_PARAMS_OFF_eccErrorNotifierMem: usize = 272;
    const ALLOC_CHANNEL_PARAMS_OFF_ProcessID: usize = 296;
    const ALLOC_CHANNEL_PARAMS_OFF_SubProcessID: usize = 300;
    const ALLOC_CHANNEL_PARAMS_OFF_encryptIv: usize = 304;
    const ALLOC_CHANNEL_PARAMS_OFF_decryptIv: usize = 316;
    const ALLOC_CHANNEL_PARAMS_OFF_hmacNonce: usize = 328;
    const ALLOC_CHANNEL_PARAMS_OFF_tpcConfigID: usize = 360;
    const ALLOC_CHANNEL_PARAMS_OFF_hHandleVASpace: usize = 368;
    type GpuNameStringBuffer = crate::v595::NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1;
    const GPU_NAME_STRING_BUFFER_SIZE: u32 = 64;
    const GPU_NAME_STRING_BUFFER_OFF_ascii: usize = 0;
    const GPU_NAME_STRING_BUFFER_OFF_unicode: usize = 64;
    type GpuNameStringParams = crate::v595::NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS;
    const GPU_NAME_STRING_PARAMS_SIZE: u32 = 68;
    const GPU_NAME_STRING_PARAMS_OFF_gpuNameStringFlags: usize = 0;
    const GPU_NAME_STRING_PARAMS_OFF_gpuNameString: usize = 4;
    type P2pCapsMatrixParams = crate::v595::NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS;
    const P2P_CAPS_MATRIX_PARAMS_SIZE: u32 = 1352;
    const P2P_CAPS_MATRIX_PARAMS_OFF_grpACount: usize = 0;
    const P2P_CAPS_MATRIX_PARAMS_OFF_grpBCount: usize = 4;
    const P2P_CAPS_MATRIX_PARAMS_OFF_gpuIdGrpA: usize = 8;
    const P2P_CAPS_MATRIX_PARAMS_OFF_gpuIdGrpB: usize = 40;
    const P2P_CAPS_MATRIX_PARAMS_OFF_p2pCaps: usize = 72;
    const P2P_CAPS_MATRIX_PARAMS_OFF_a2bOptimalReadCes: usize = 328;
    const P2P_CAPS_MATRIX_PARAMS_OFF_a2bOptimalWriteCes: usize = 584;
    const P2P_CAPS_MATRIX_PARAMS_OFF_b2aOptimalReadCes: usize = 840;
    const P2P_CAPS_MATRIX_PARAMS_OFF_b2aOptimalWriteCes: usize = 1096;
    type TsgParams = crate::v595::NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS;
    const TSG_PARAMS_SIZE: u32 = 20;
    const TSG_PARAMS_OFF_hObjectError: usize = 0;
    const TSG_PARAMS_OFF_hObjectEccError: usize = 4;
    const TSG_PARAMS_OFF_hVASpace: usize = 8;
    const TSG_PARAMS_OFF_engineType: usize = 12;
    const TSG_PARAMS_OFF_bIsCallingContextVgpuPlugin: usize = 16;
    const TSG_PARAMS_OFF_reserved: usize = 20;
    const TSG_PARAMS_OFF_internalFlags: usize = 20;
    type UvmFreeParams = crate::v595::UVM_FREE_PARAMS;
    const UVM_FREE_PARAMS_SIZE: u32 = 16;
    const UVM_FREE_PARAMS_OFF_base: usize = 0;
    const UVM_FREE_PARAMS_OFF_length: usize = 16;
    const UVM_FREE_PARAMS_OFF_rmStatus: usize = 8;
    type UvmUnregisterChannelParams = crate::v595::UVM_UNREGISTER_CHANNEL_PARAMS;
    const UVM_UNREGISTER_CHANNEL_PARAMS_SIZE: u32 = 12;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_gpuUuid: usize = 12;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_hClient: usize = 0;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_hChannel: usize = 4;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_rmStatus: usize = 8;
    const CLASS_DISPLAYLESS: Option<u32> = Some(41091);
    const CTRL_VD_GET_DEFAULT_EDID: Option<u32> = Some(2692940035);
    const CTRL_VD_GET_MAX_PIXELS: Option<u32> = Some(2692940038);
    const CTRL_VD_GET_MAX_RESOLUTION: Option<u32> = Some(2692940034);
    const CTRL_VD_GET_NUM_HEADS: Option<u32> = Some(2692940033);
    const CTRL_VD_IS_ACTIVE: Option<u32> = Some(2692940036);
    const CTRL_VD_IS_CONNECTED: Option<u32> = Some(2692940037);
}

/// The ABI of driver 610.57.04. See [`RmAbi`].
#[cfg(feature = "v610")]
#[derive(Clone, Copy, Debug)]
pub struct V610;

#[cfg(feature = "v610")]
impl RmAbi for V610 {
    const VERSION: DriverVersion = DriverVersion::V610;
    type AllocChannelParams = crate::v610::NV_CHANNEL_ALLOC_PARAMS;
    const ALLOC_CHANNEL_PARAMS_SIZE: u32 = 376;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectError: usize = 0;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectBuffer: usize = 4;
    const ALLOC_CHANNEL_PARAMS_OFF_gpFifoOffset: usize = 8;
    const ALLOC_CHANNEL_PARAMS_OFF_gpFifoEntries: usize = 16;
    const ALLOC_CHANNEL_PARAMS_OFF_flags: usize = 20;
    const ALLOC_CHANNEL_PARAMS_OFF_hContextShare: usize = 24;
    const ALLOC_CHANNEL_PARAMS_OFF_hVASpace: usize = 28;
    const ALLOC_CHANNEL_PARAMS_OFF_hUserdMemory: usize = 36;
    const ALLOC_CHANNEL_PARAMS_OFF_userdOffset: usize = 72;
    const ALLOC_CHANNEL_PARAMS_OFF_engineType: usize = 136;
    const ALLOC_CHANNEL_PARAMS_OFF_cid: usize = 140;
    const ALLOC_CHANNEL_PARAMS_OFF_subDeviceId: usize = 144;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectEccError: usize = 148;
    const ALLOC_CHANNEL_PARAMS_OFF_instanceMem: usize = 152;
    const ALLOC_CHANNEL_PARAMS_OFF_userdMem: usize = 176;
    const ALLOC_CHANNEL_PARAMS_OFF_ramfcMem: usize = 200;
    const ALLOC_CHANNEL_PARAMS_OFF_mthdbufMem: usize = 224;
    const ALLOC_CHANNEL_PARAMS_OFF_hPhysChannelGroup: usize = 248;
    const ALLOC_CHANNEL_PARAMS_OFF_internalFlags: usize = 252;
    const ALLOC_CHANNEL_PARAMS_OFF_errorNotifierMem: usize = 256;
    const ALLOC_CHANNEL_PARAMS_OFF_eccErrorNotifierMem: usize = 280;
    const ALLOC_CHANNEL_PARAMS_OFF_ProcessID: usize = 304;
    const ALLOC_CHANNEL_PARAMS_OFF_SubProcessID: usize = 308;
    const ALLOC_CHANNEL_PARAMS_OFF_encryptIv: usize = 312;
    const ALLOC_CHANNEL_PARAMS_OFF_decryptIv: usize = 324;
    const ALLOC_CHANNEL_PARAMS_OFF_hmacNonce: usize = 336;
    const ALLOC_CHANNEL_PARAMS_OFF_tpcConfigID: usize = 368;
    const ALLOC_CHANNEL_PARAMS_OFF_hHandleVASpace: usize = 32;
    type GpuNameStringBuffer = crate::v610::NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1;
    const GPU_NAME_STRING_BUFFER_SIZE: u32 = 64;
    const GPU_NAME_STRING_BUFFER_OFF_ascii: usize = 0;
    const GPU_NAME_STRING_BUFFER_OFF_unicode: usize = 64;
    type GpuNameStringParams = crate::v610::NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS;
    const GPU_NAME_STRING_PARAMS_SIZE: u32 = 68;
    const GPU_NAME_STRING_PARAMS_OFF_gpuNameStringFlags: usize = 0;
    const GPU_NAME_STRING_PARAMS_OFF_gpuNameString: usize = 4;
    type P2pCapsMatrixParams = crate::v610::NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS;
    const P2P_CAPS_MATRIX_PARAMS_SIZE: u32 = 1352;
    const P2P_CAPS_MATRIX_PARAMS_OFF_grpACount: usize = 0;
    const P2P_CAPS_MATRIX_PARAMS_OFF_grpBCount: usize = 4;
    const P2P_CAPS_MATRIX_PARAMS_OFF_gpuIdGrpA: usize = 8;
    const P2P_CAPS_MATRIX_PARAMS_OFF_gpuIdGrpB: usize = 40;
    const P2P_CAPS_MATRIX_PARAMS_OFF_p2pCaps: usize = 72;
    const P2P_CAPS_MATRIX_PARAMS_OFF_a2bOptimalReadCes: usize = 328;
    const P2P_CAPS_MATRIX_PARAMS_OFF_a2bOptimalWriteCes: usize = 584;
    const P2P_CAPS_MATRIX_PARAMS_OFF_b2aOptimalReadCes: usize = 840;
    const P2P_CAPS_MATRIX_PARAMS_OFF_b2aOptimalWriteCes: usize = 1096;
    type TsgParams = crate::v610::NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS;
    const TSG_PARAMS_SIZE: u32 = 20;
    const TSG_PARAMS_OFF_hObjectError: usize = 0;
    const TSG_PARAMS_OFF_hObjectEccError: usize = 4;
    const TSG_PARAMS_OFF_hVASpace: usize = 8;
    const TSG_PARAMS_OFF_engineType: usize = 12;
    const TSG_PARAMS_OFF_bIsCallingContextVgpuPlugin: usize = 16;
    const TSG_PARAMS_OFF_reserved: usize = 20;
    const TSG_PARAMS_OFF_internalFlags: usize = 20;
    type UvmFreeParams = crate::v610::UVM_FREE_PARAMS;
    const UVM_FREE_PARAMS_SIZE: u32 = 16;
    const UVM_FREE_PARAMS_OFF_base: usize = 0;
    const UVM_FREE_PARAMS_OFF_length: usize = 16;
    const UVM_FREE_PARAMS_OFF_rmStatus: usize = 8;
    type UvmUnregisterChannelParams = crate::v610::UVM_UNREGISTER_CHANNEL_PARAMS;
    const UVM_UNREGISTER_CHANNEL_PARAMS_SIZE: u32 = 12;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_gpuUuid: usize = 12;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_hClient: usize = 0;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_hChannel: usize = 4;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_rmStatus: usize = 8;
    const CLASS_DISPLAYLESS: Option<u32> = Some(41091);
    const CTRL_VD_GET_DEFAULT_EDID: Option<u32> = Some(2692940035);
    const CTRL_VD_GET_MAX_PIXELS: Option<u32> = Some(2692940038);
    const CTRL_VD_GET_MAX_RESOLUTION: Option<u32> = Some(2692940034);
    const CTRL_VD_GET_NUM_HEADS: Option<u32> = Some(2692940033);
    const CTRL_VD_IS_ACTIVE: Option<u32> = Some(2692940036);
    const CTRL_VD_IS_CONNECTED: Option<u32> = Some(2692940037);
}

/// The ABI of driver 615.71.09. See [`RmAbi`].
#[cfg(feature = "v615")]
#[derive(Clone, Copy, Debug)]
pub struct V615;

#[cfg(feature = "v615")]
impl RmAbi for V615 {
    const VERSION: DriverVersion = DriverVersion::V615;
    type AllocChannelParams = crate::v615::NV_CHANNEL_ALLOC_PARAMS;
    const ALLOC_CHANNEL_PARAMS_SIZE: u32 = 376;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectError: usize = 0;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectBuffer: usize = 4;
    const ALLOC_CHANNEL_PARAMS_OFF_gpFifoOffset: usize = 8;
    const ALLOC_CHANNEL_PARAMS_OFF_gpFifoEntries: usize = 16;
    const ALLOC_CHANNEL_PARAMS_OFF_flags: usize = 20;
    const ALLOC_CHANNEL_PARAMS_OFF_hContextShare: usize = 24;
    const ALLOC_CHANNEL_PARAMS_OFF_hVASpace: usize = 28;
    const ALLOC_CHANNEL_PARAMS_OFF_hUserdMemory: usize = 36;
    const ALLOC_CHANNEL_PARAMS_OFF_userdOffset: usize = 72;
    const ALLOC_CHANNEL_PARAMS_OFF_engineType: usize = 136;
    const ALLOC_CHANNEL_PARAMS_OFF_cid: usize = 140;
    const ALLOC_CHANNEL_PARAMS_OFF_subDeviceId: usize = 144;
    const ALLOC_CHANNEL_PARAMS_OFF_hObjectEccError: usize = 148;
    const ALLOC_CHANNEL_PARAMS_OFF_instanceMem: usize = 152;
    const ALLOC_CHANNEL_PARAMS_OFF_userdMem: usize = 176;
    const ALLOC_CHANNEL_PARAMS_OFF_ramfcMem: usize = 200;
    const ALLOC_CHANNEL_PARAMS_OFF_mthdbufMem: usize = 224;
    const ALLOC_CHANNEL_PARAMS_OFF_hPhysChannelGroup: usize = 248;
    const ALLOC_CHANNEL_PARAMS_OFF_internalFlags: usize = 252;
    const ALLOC_CHANNEL_PARAMS_OFF_errorNotifierMem: usize = 256;
    const ALLOC_CHANNEL_PARAMS_OFF_eccErrorNotifierMem: usize = 280;
    const ALLOC_CHANNEL_PARAMS_OFF_ProcessID: usize = 304;
    const ALLOC_CHANNEL_PARAMS_OFF_SubProcessID: usize = 308;
    const ALLOC_CHANNEL_PARAMS_OFF_encryptIv: usize = 312;
    const ALLOC_CHANNEL_PARAMS_OFF_decryptIv: usize = 324;
    const ALLOC_CHANNEL_PARAMS_OFF_hmacNonce: usize = 336;
    const ALLOC_CHANNEL_PARAMS_OFF_tpcConfigID: usize = 368;
    const ALLOC_CHANNEL_PARAMS_OFF_hHandleVASpace: usize = 32;
    type GpuNameStringBuffer = crate::v615::NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1;
    const GPU_NAME_STRING_BUFFER_SIZE: u32 = 64;
    const GPU_NAME_STRING_BUFFER_OFF_ascii: usize = 0;
    const GPU_NAME_STRING_BUFFER_OFF_unicode: usize = 64;
    type GpuNameStringParams = crate::v615::NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS;
    const GPU_NAME_STRING_PARAMS_SIZE: u32 = 68;
    const GPU_NAME_STRING_PARAMS_OFF_gpuNameStringFlags: usize = 0;
    const GPU_NAME_STRING_PARAMS_OFF_gpuNameString: usize = 4;
    type P2pCapsMatrixParams = crate::v615::NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS;
    const P2P_CAPS_MATRIX_PARAMS_SIZE: u32 = 1352;
    const P2P_CAPS_MATRIX_PARAMS_OFF_grpACount: usize = 0;
    const P2P_CAPS_MATRIX_PARAMS_OFF_grpBCount: usize = 4;
    const P2P_CAPS_MATRIX_PARAMS_OFF_gpuIdGrpA: usize = 8;
    const P2P_CAPS_MATRIX_PARAMS_OFF_gpuIdGrpB: usize = 40;
    const P2P_CAPS_MATRIX_PARAMS_OFF_p2pCaps: usize = 72;
    const P2P_CAPS_MATRIX_PARAMS_OFF_a2bOptimalReadCes: usize = 328;
    const P2P_CAPS_MATRIX_PARAMS_OFF_a2bOptimalWriteCes: usize = 584;
    const P2P_CAPS_MATRIX_PARAMS_OFF_b2aOptimalReadCes: usize = 840;
    const P2P_CAPS_MATRIX_PARAMS_OFF_b2aOptimalWriteCes: usize = 1096;
    type TsgParams = crate::v615::NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS;
    const TSG_PARAMS_SIZE: u32 = 28;
    const TSG_PARAMS_OFF_hObjectError: usize = 0;
    const TSG_PARAMS_OFF_hObjectEccError: usize = 4;
    const TSG_PARAMS_OFF_hVASpace: usize = 8;
    const TSG_PARAMS_OFF_engineType: usize = 12;
    const TSG_PARAMS_OFF_bIsCallingContextVgpuPlugin: usize = 16;
    const TSG_PARAMS_OFF_reserved: usize = 20;
    const TSG_PARAMS_OFF_internalFlags: usize = 24;
    type UvmFreeParams = crate::v615::UVM_FREE_PARAMS;
    const UVM_FREE_PARAMS_SIZE: u32 = 16;
    const UVM_FREE_PARAMS_OFF_base: usize = 0;
    const UVM_FREE_PARAMS_OFF_length: usize = 16;
    const UVM_FREE_PARAMS_OFF_rmStatus: usize = 8;
    type UvmUnregisterChannelParams = crate::v615::UVM_UNREGISTER_CHANNEL_PARAMS;
    const UVM_UNREGISTER_CHANNEL_PARAMS_SIZE: u32 = 12;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_gpuUuid: usize = 12;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_hClient: usize = 0;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_hChannel: usize = 4;
    const UVM_UNREGISTER_CHANNEL_PARAMS_OFF_rmStatus: usize = 8;
    const CLASS_DISPLAYLESS: Option<u32> = Some(41091);
    const CTRL_VD_GET_DEFAULT_EDID: Option<u32> = Some(2692940035);
    const CTRL_VD_GET_MAX_PIXELS: Option<u32> = Some(2692940038);
    const CTRL_VD_GET_MAX_RESOLUTION: Option<u32> = Some(2692940034);
    const CTRL_VD_GET_NUM_HEADS: Option<u32> = Some(2692940033);
    const CTRL_VD_IS_ACTIVE: Option<u32> = Some(2692940036);
    const CTRL_VD_IS_CONNECTED: Option<u32> = Some(2692940037);
}
