// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Silas Müller <github@silasmueller.de>
// SPDX-FileCopyrightText: 2026 Universität Stuttgart, IKR
//! The driver-version-specific half of 595.99.02.
//!
//! Everything here differs from at least one other version in
//! abi.toml. The layout of every type was measured from the
//! headers of this version alone -- see
//!   manifests/595.99.02.json
//! and the `assert_layout!` below, whose numbers come from it.
//!
//! Generated by `cargo xtask abi`. Do not edit.

pub use super::stable::*;

/// Driver versions this module's layouts were measured on.
pub const VERIFIED_VERSIONS: &[&str] = &["595.99.02"];

/// Layout verified for: 595.99.02
pub const NV_ESC_NUMA_INFO: u32 = 215;
/// Layout verified for: 595.99.02
pub const NV_ESC_SET_NUMA_STATUS: u32 = 216;
/// Layout verified for: 595.99.02
pub const NV_IOCTL_NUMA_INFO_MAX_OFFLINE_ADDRESSES: u32 = 64;
/// Layout verified for: 595.99.02
pub const NV_IOCTL_NUMA_STATUS_DISABLED: u32 = 0;
/// Layout verified for: 595.99.02
pub const NV_IOCTL_NUMA_STATUS_OFFLINE: u32 = 1;
/// Layout verified for: 595.99.02
pub const NV_IOCTL_NUMA_STATUS_ONLINE_IN_PROGRESS: u32 = 2;
/// Layout verified for: 595.99.02
pub const NV_IOCTL_NUMA_STATUS_ONLINE: u32 = 3;
/// Layout verified for: 595.99.02
pub const NV_IOCTL_NUMA_STATUS_ONLINE_FAILED: u32 = 4;
/// Layout verified for: 595.99.02
pub const NV_IOCTL_NUMA_STATUS_OFFLINE_IN_PROGRESS: u32 = 5;
/// Layout verified for: 595.99.02
pub const NV_IOCTL_NUMA_STATUS_OFFLINE_FAILED: u32 = 6;
/// Layout verified for: 595.99.02
pub const NVOS32_ATTR2_ENABLE_LOCALIZED_MEMORY_UGPU_COUNT: u32 = 2;
/// Layout verified for: 595.99.02
pub const NVOS33_FLAGS_BUS_DEFAULT: u32 = 0;
/// Layout verified for: 595.99.02
pub const NVOS33_FLAGS_BUS_COHERENT_LINK: u32 = 1;
/// Layout verified for: 595.99.02
pub const NVOS33_FLAGS_BUS_PCIE: u32 = 2;
/// Layout verified for: 595.99.02
pub const NV2080_NOTIFIERS_VRR_SET_TIMEOUT: u32 = 179;
/// Layout verified for: 595.99.02
pub const NV2080_NOTIFIERS_RESERVED_198: u32 = 198;
/// Layout verified for: 595.99.02
pub const NV2080_NOTIFIERS_MAXCOUNT: u32 = 199;
/// Layout verified for: 595.99.02
pub const NVA083_GRID_DISPLAYLESS: u32 = 41091;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_RESERVED: u32 = 0;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_VIRTUAL_DISPLAY: u32 = 1;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_CMD_NULL: u32 = 2692939776;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_CMD_VIRTUAL_DISPLAY_GET_NUM_HEADS: u32 = 2692940033;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_VIRTUAL_DISPLAY_GET_NUM_HEADS_PARAMS_MESSAGE_ID: u32 = 1;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_CMD_VIRTUAL_DISPLAY_GET_MAX_RESOLUTION: u32 = 2692940034;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_VIRTUAL_DISPLAY_GET_MAX_RESOLUTION_PARAMS_MESSAGE_ID: u32 = 2;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_CMD_VIRTUAL_DISPLAY_GET_DEFAULT_EDID: u32 = 2692940035;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_VIRTUAL_DISPLAY_GET_DEFAULT_EDID_PARAMS_MESSAGE_ID: u32 = 3;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_CMD_CONNECTOR_INFO_TYPE_DVI_D: u32 = 0;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_CMD_CONNECTOR_INFO_TYPE_VGA_15_PIN: u32 = 1;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_CMD_VIRTUAL_DISPLAY_IS_ACTIVE: u32 = 2692940036;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_VIRTUAL_DISPLAY_IS_ACTIVE_PARAMS_MESSAGE_ID: u32 = 4;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_CMD_VIRTUAL_DISPLAY_IS_CONNECTED: u32 = 2692940037;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_VIRTUAL_DISPLAY_IS_CONNECTED_PARAMS_MESSAGE_ID: u32 = 5;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_CMD_VIRTUAL_DISPLAY_GET_MAX_PIXELS: u32 = 2692940038;
/// Layout verified for: 595.99.02
pub const NVA083_CTRL_VIRTUAL_DISPLAY_GET_MAX_PIXELS_PARAMS_MESSAGE_ID: u32 = 6;
/// Layout verified for: 595.99.02
pub const NV0000_CTRL_SYSTEM_CHIPSET_FLAG_BAR1_UNALIGNED_ACCESS_NO: u32 = 0;
/// Layout verified for: 595.99.02
pub const NV0000_CTRL_SYSTEM_CHIPSET_FLAG_BAR1_UNALIGNED_ACCESS_YES: u32 = 1;
/// Layout verified for: 595.99.02
pub const NV2080_GPU_CMD_GPU_GET_GID_FLAGS_MODE_GPU: u32 = 0;
/// Layout verified for: 595.99.02
pub const NV2080_GPU_CMD_GPU_GET_GID_FLAGS_MODE_UGPU: u32 = 1;
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_CMD_BUS_GET_C2C_INFO_MAX_C2C_INSTANCES: u32 = 2;
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_CMD_BUS_GET_C2C_INFO_MAX_C2C_LINKS_PER_INSTANCE: u32 = 7;
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_CMD_BUS_GET_C2C_INFO_MAX_C2C_LINKS: u32 = 14;
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_CMD_BUS_SET_C2C_LPWR_IDLE_THRESHOLD: u32 = 545265718;
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_CMD_BUS_SET_C2C_LPWR_IDLE_THRESHOLD_PARAMS_MESSAGE_ID: u32 = 54;
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_CMD_BUS_GET_C2C_PACKET_COUNTERS: u32 = 545265719;
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_CMD_BUS_GET_C2C_PACKET_COUNTERS_PARAMS_MESSAGE_ID: u32 = 55;
/// Layout verified for: 595.99.02
pub const NV0000_CTRL_CMD_GPU_DISABLE_NVLINK_INIT: u32 = 641;
/// Layout verified for: 595.99.02
pub const NV0000_CTRL_GPU_DISABLE_NVLINK_INIT_PARAMS_MESSAGE_ID: u32 = 129;
/// Layout verified for: 595.99.02
pub const NV0000_CTRL_CMD_GPU_PCI_READ_WRITE_DATA_SIZE_08: u32 = 0;
/// Layout verified for: 595.99.02
pub const NV0000_CTRL_CMD_GPU_PCI_READ_WRITE_DATA_SIZE_16: u32 = 1;
/// Layout verified for: 595.99.02
pub const NV0000_CTRL_CMD_GPU_PCI_READ_WRITE_DATA_SIZE_32: u32 = 2;
/// Layout verified for: 595.99.02
pub const NV0000_CTRL_CMD_GPU_PCI_READ_WRITE: u32 = 657;
/// Layout verified for: 595.99.02
pub const NV0000_CTRL_GPU_PCI_READ_WRITE_PARAMS_MESSAGE_ID: u32 = 145;
/// Layout verified for: 595.99.02
pub const UVM_PMA_MAX_LOCALIZED_REGION_COUNT: u32 = 2;
/// Layout verified for: 595.99.02
pub const UVM_MAX_RANGE_GROUPS_PER_IOCTL_CALL: u32 = 32;
/// Layout verified for: 595.99.02
pub const NV_ERR_OPERATION_ABORTED: _bindgen_ty_1 = 139;
/// Layout verified for: 595.99.02
pub const NV_ERR_DMA_XFER_FAILED: _bindgen_ty_1 = 140;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct offline_addresses {
    pub addresses: [u64; 64usize],
    pub numEntries: u32,
}
impl Default for offline_addresses {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
pub type nv_offline_addresses_t = offline_addresses;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nv_ioctl_numa_info {
    pub nid: i32,
    pub status: i32,
    pub memblock_size: u64,
    pub numa_mem_addr: u64,
    pub numa_mem_size: u64,
    pub use_auto_online: u8,
    pub offline_addresses: nv_offline_addresses_t,
}
impl Default for nv_ioctl_numa_info {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
pub type nv_ioctl_numa_info_t = nv_ioctl_numa_info;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nv_ioctl_set_numa_status {
    pub status: i32,
}
/// Layout verified for: 595.99.02
pub type nv_ioctl_set_numa_status_t = nv_ioctl_set_numa_status;
/// Layout verified for: 595.99.02
pub type nv_ioctl_query_device_intr_t = nv_ioctl_query_device_intr;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV_CHANNEL_ALLOC_PARAMS {
    pub hObjectError: NvHandle,
    pub hObjectBuffer: NvHandle,
    pub gpFifoOffset: NvU64,
    pub gpFifoEntries: NvU32,
    pub flags: NvU32,
    pub hContextShare: NvHandle,
    pub hVASpace: NvHandle,
    pub hUserdMemory: [NvHandle; 8usize],
    pub userdOffset: [NvU64; 8usize],
    pub engineType: NvU32,
    pub cid: NvU32,
    pub subDeviceId: NvU32,
    pub hObjectEccError: NvHandle,
    pub instanceMem: NV_MEMORY_DESC_PARAMS,
    pub userdMem: NV_MEMORY_DESC_PARAMS,
    pub ramfcMem: NV_MEMORY_DESC_PARAMS,
    pub mthdbufMem: NV_MEMORY_DESC_PARAMS,
    pub hPhysChannelGroup: NvHandle,
    pub internalFlags: NvU32,
    pub errorNotifierMem: NV_MEMORY_DESC_PARAMS,
    pub eccErrorNotifierMem: NV_MEMORY_DESC_PARAMS,
    pub ProcessID: NvU32,
    pub SubProcessID: NvU32,
    pub encryptIv: [NvU32; 3usize],
    pub decryptIv: [NvU32; 3usize],
    pub hmacNonce: [NvU32; 8usize],
    pub tpcConfigID: NvU32,
}
/// Layout verified for: 595.99.02
pub type NV_CHANNELGPFIFO_ALLOCATION_PARAMETERS = NV_CHANNEL_ALLOC_PARAMS;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS {
    pub hObjectError: NvHandle,
    pub hObjectEccError: NvHandle,
    pub hVASpace: NvHandle,
    pub engineType: NvU32,
    pub bIsCallingContextVgpuPlugin: NvBool,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_ECC_INJECTION_SUPPORTED_PARAMS {
    pub unit: NvU32,
    pub bCorrectableSupported: NvBool,
    pub bUncorrectableSupported: NvBool,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NVA083_CTRL_VIRTUAL_DISPLAY_GET_NUM_HEADS_PARAMS {
    pub numHeads: NvU32,
    pub maxNumHeads: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NVA083_CTRL_VIRTUAL_DISPLAY_GET_MAX_RESOLUTION_PARAMS {
    pub headIndex: NvU32,
    pub maxHResolution: NvU32,
    pub maxVResolution: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVA083_CTRL_VIRTUAL_DISPLAY_GET_DEFAULT_EDID_PARAMS {
    pub pEdidBuffer: NvP64,
    pub edidSize: NvU32,
    pub connectorType: NvU8,
}
impl Default for NVA083_CTRL_VIRTUAL_DISPLAY_GET_DEFAULT_EDID_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NVA083_CTRL_VIRTUAL_DISPLAY_IS_ACTIVE_PARAMS {
    pub isDisplayActive: NvBool,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NVA083_CTRL_VIRTUAL_DISPLAY_IS_CONNECTED_PARAMS {
    pub isDisplayConnected: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NVA083_CTRL_VIRTUAL_DISPLAY_GET_MAX_PIXELS_PARAMS {
    pub maxPixels: NvU64,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV0080_CTRL_GR_GET_INFO_V2_PARAMS {
    pub grInfoListSize: NvU32,
    pub grInfoList: [NV0080_CTRL_GR_INFO; 59usize],
    pub grRouteInfo: NV0080_CTRL_GR_ROUTE_INFO,
}
impl Default for NV0080_CTRL_GR_GET_INFO_V2_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_GR_GET_SM_TO_GPC_TPC_MAPPINGS_PARAMS {
    pub smId: [NV2080_CTRL_GR_GET_SM_TO_GPC_TPC_MAPPINGS_PARAMS__bindgen_ty_1; 240usize],
    pub smCount: NvU32,
    pub grRouteInfo: NV2080_CTRL_GR_ROUTE_INFO,
}
impl Default for NV2080_CTRL_GR_GET_SM_TO_GPC_TPC_MAPPINGS_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_GR_GET_GLOBAL_SM_ORDER_PARAMS {
    pub globalSmId: [NV2080_CTRL_GR_GET_GLOBAL_SM_ORDER_PARAMS__bindgen_ty_1; 512usize],
    pub numSm: NvU16,
    pub numTpc: NvU16,
    pub grRouteInfo: NV2080_CTRL_GR_ROUTE_INFO,
}
impl Default for NV2080_CTRL_GR_GET_GLOBAL_SM_ORDER_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GR_GET_GLOBAL_SM_ORDER_PARAMS__bindgen_ty_1 {
    pub gpcId: NvU16,
    pub localTpcId: NvU16,
    pub localSmId: NvU16,
    pub globalTpcId: NvU16,
    pub virtualGpcId: NvU16,
    pub migratableTpcId: NvU16,
    pub ugpuId: NvU16,
    pub physicalCpcId: NvU16,
    pub virtualTpcId: NvU16,
}
/// Layout verified for: 595.99.02
pub type NV2080_CTRL_GR_GET_INFO_V2_PARAMS = NV0080_CTRL_GR_GET_INFO_V2_PARAMS;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GR_TEST_CTXSW_ERROR_LOGS_PARAMS {
    pub expectedCharCount: NvU32,
    pub bUseInterrupt: NvBool,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV0000_CTRL_SYSTEM_GET_CHIPSET_INFO_PARAMS {
    pub vendorId: NvU16,
    pub deviceId: NvU16,
    pub subSysVendorId: NvU16,
    pub subSysDeviceId: NvU16,
    pub HBvendorId: NvU16,
    pub HBdeviceId: NvU16,
    pub HBsubSysVendorId: NvU16,
    pub HBsubSysDeviceId: NvU16,
    pub sliBondId: NvU32,
    pub vendorNameString: [NvU8; 32usize],
    pub subSysVendorNameString: [NvU8; 32usize],
    pub chipsetNameString: [NvU8; 32usize],
    pub sliBondNameString: [NvU8; 32usize],
    pub flags: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS {
    pub grpACount: NvU32,
    pub grpBCount: NvU32,
    pub gpuIdGrpA: [NvU32; 8usize],
    pub gpuIdGrpB: [NvU32; 8usize],
    pub p2pCaps: [[NvU32; 8usize]; 8usize],
    pub a2bOptimalReadCes: [[NvU32; 8usize]; 8usize],
    pub a2bOptimalWriteCes: [[NvU32; 8usize]; 8usize],
    pub b2aOptimalReadCes: [[NvU32; 8usize]; 8usize],
    pub b2aOptimalWriteCes: [[NvU32; 8usize]; 8usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Copy, Clone)]
pub struct NV0000_CTRL_SYSTEM_NVPCF_GET_POWER_MODE_INFO_PARAMS {
    pub supportedFuncs: NvU32,
    pub gpuId: NvU32,
    pub tpp: NvU32,
    pub ratedTgp: NvU32,
    pub subFunc: NvU32,
    pub ctgpOffsetmW: NvS32,
    pub targetTppOffsetmW: NvS32,
    pub maxOutputOffsetmW: NvS32,
    pub minOutputOffsetmW: NvS32,
    pub ctgpBattOffsetmW: NvS32,
    pub targetTppBattOffsetmW: NvS32,
    pub maxOutputBattOffsetmW: NvS32,
    pub minOutputBattOffsetmW: NvS32,
    pub dcRosReserveOverridemW: NvU32,
    pub dcTspLongTimescaleLimitmA: NvU32,
    pub dcTspLongTimescaleLimitOverridemA: NvU32,
    pub dcTspShortTimescaleLimitmA: NvU32,
    pub dcTspShortTimescaleLimitOverridemA: NvU32,
    pub bEnableForAC: NvBool,
    pub bEnableForDC: NvBool,
    pub version: NvU8,
    pub samplingPeriodmS: NvU16,
    pub samplingMulti: NvU16,
    pub filterType: NvU8,
    pub filterParam: NV0000_CTRL_SYSTEM_NVPCF_GET_POWER_MODE_INFO_PARAMS__bindgen_ty_1,
    pub filterReserved: NvU16,
    pub bIsBoostController: NvBool,
    pub incRatio: NvU16,
    pub decRatio: NvU16,
    pub bSupportBatt: NvBool,
    pub cpuType: NvU8,
    pub gpuType: NvU8,
    pub sysPwrIndex: NvU32,
    pub sysPwrGetInfo: [NV0000_CTRL_CMD_SYSTEM_GET_SYSTEM_POWER_LIMIT; 32usize],
    pub bIsTspSupported: NvBool,
    pub sysPwrLimitsTableVersion: NvU8,
    pub type_: NvU32,
    pub cpuTdpmw: NvU32,
    pub cpuTdpControlType: QBOOST_CPU_TDP_CONTROL_TYPE,
}
impl Default for NV0000_CTRL_SYSTEM_NVPCF_GET_POWER_MODE_INFO_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_GPU_GET_INFO_V2_PARAMS {
    pub gpuInfoListSize: NvU32,
    pub gpuInfoList: [NV2080_CTRL_GPU_INFO; 70usize],
}
impl Default for NV2080_CTRL_GPU_GET_INFO_V2_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS {
    pub gpuNameStringFlags: NvU32,
    pub gpuNameString: NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1,
}
impl Default for NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1 {
    pub ascii: [NvU8; 64usize],
}
impl Default for NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_GPU_QUERY_ECC_STATUS_PARAMS {
    pub units: [NV2080_CTRL_GPU_QUERY_ECC_UNIT_STATUS; 41usize],
    pub bFatalPoisonError: NvBool,
    pub uncorrectableError: NvU8,
    pub flags: NvU32,
    pub grRouteInfo: NV2080_CTRL_GR_ROUTE_INFO,
}
impl Default for NV2080_CTRL_GPU_QUERY_ECC_STATUS_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GPU_GET_PES_INFO_PARAMS {
    pub gpcId: NvU32,
    pub numPesInGpc: NvU32,
    pub activePesMask: NvU32,
    pub maxTpcPerGpcCount: NvU32,
    pub tpcToPesMap: [NvU32; 10usize],
}
/// Layout verified for: 595.99.02
pub type NV2080_CTRL_GPU_GET_CACHED_INFO_PARAMS = NV2080_CTRL_GPU_GET_INFO_V2_PARAMS;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_GPU_GET_ENGINE_LOAD_TIMES_PARAMS {
    pub engineCount: NvU32,
    pub engineList: [NvU32; 200usize],
    pub engineStateLoadTime: [NvU64; 200usize],
    pub engineIsInit: [NvBool; 200usize],
}
impl Default for NV2080_CTRL_GPU_GET_ENGINE_LOAD_TIMES_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_GPU_GET_ID_NAME_MAPPING_PARAMS {
    pub engineCount: NvU32,
    pub engineID: [NvU32; 200usize],
    pub engineName: [[::core::ffi::c_char; 100usize]; 200usize],
}
impl Default for NV2080_CTRL_GPU_GET_ID_NAME_MAPPING_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GPU_SKYLINE_INFO {
    pub skylineVgpcSize: [NvU8; 32usize],
    pub singletonVgpcMask: NvU32,
    pub maxInstances: NvU32,
    pub computeSizeFlag: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GPU_GET_SKYLINE_INFO_PARAMS {
    pub skylineTable: [NV2080_CTRL_GPU_SKYLINE_INFO; 9usize],
    pub validEntries: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GPU_COMPUTE_PROFILE {
    pub computeSize: NvU8,
    pub gfxGpcCount: NvU32,
    pub gpcCount: NvU32,
    pub veidCount: NvU32,
    pub smCount: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GPU_GET_COMPUTE_PROFILES_PARAMS {
    pub partitionFlag: NvU32,
    pub profileCount: NvU32,
    pub profiles: [NV2080_CTRL_GPU_COMPUTE_PROFILE; 8usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_GET_GPU_FABRIC_PROBE_INFO_PARAMS {
    pub state: NvU8,
    pub status: NV_STATUS,
    pub clusterUuid: [NvU8; 16usize],
    pub fabricPartitionId: NvU16,
    pub fabricCaps: NvU64,
    pub fabricCliqueId: NvU32,
    pub fabricHealthMask: NvU32,
    pub fabricHealthSummary: NvU8,
}
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_GPU_RECOVERY_ACTION_GPU_RESET: NV2080_CTRL_GPU_RECOVERY_ACTION = 1;
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_GPU_RECOVERY_ACTION_NODE_REBOOT: NV2080_CTRL_GPU_RECOVERY_ACTION = 2;
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_GPU_RECOVERY_ACTION_RECOVER_IMEX_DOMAIN: NV2080_CTRL_GPU_RECOVERY_ACTION = 5;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GPU_RUSD_SET_FEATURES_PARAMS {
    pub permanentPolledDataMask: NvU64,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GPU_VGA_SR_READ_WRITE_PARAMS {
    pub bWrite: NvBool,
    pub head: NvU32,
    pub index: NvU8,
    pub data: NvU8,
}
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_GPU_INJECT_ERROR_MESSAGE_QUEUE: NV2080_CTRL_GPU_INJECT_ERROR_TYPE = 0;
/// Layout verified for: 595.99.02
pub const NV2080_CTRL_GPU_INJECT_ERROR__COUNT: NV2080_CTRL_GPU_INJECT_ERROR_TYPE = 1;
/// Layout verified for: 595.99.02
pub type NV2080_CTRL_GPU_INJECT_ERROR_TYPE = ::core::ffi::c_uint;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GPU_ERROR_INJECTION_CONTROL_PARAMS {
    pub errorType: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GPU_CHECK_MEM_SUBSYS_ERROR_PARAMS {
    pub flags: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_GPU_GET_DEFAULT_TIMEOUT_PARAMS {
    pub defaultTimeout: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV0080_CTRL_MSENC_GET_CAPS_V2_PARAMS {
    pub capsTbl: [NvU8; 6usize],
    pub instanceId: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV0080_CTRL_BSP_GET_CAPS_PARAMS {
    pub capsTblSize: NvU32,
    pub capsTbl: NvP64,
    pub instanceId: NvU32,
}
impl Default for NV0080_CTRL_BSP_GET_CAPS_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV0080_CTRL_BSP_GET_CAPS_PARAMS_V2 {
    pub capsTbl: [NvU8; 8usize],
    pub instanceId: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_FIFO_CHANNEL_PREEMPTIVE_REMOVAL_PARAMS {
    pub hChannel: NvHandle,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_FIFO_OBJSCHED_SW_GET_LOG_ENTRY {
    pub timestampNs: NvU64,
    pub timeRunTotalNs: NvS64,
    pub timeRunNs: NvU32,
    pub swrlId: NvU32,
    pub targetTimeSlice: NvU32,
    pub cumulativePreemptionTime: NvU64,
    pub cumulativeIdleTime: NvU64,
    pub weight: NvU32,
    pub counters: [NvU64; 8usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_FIFO_OBJSCHED_SW_GET_LOG_PARAMS {
    pub engineId: NvU32,
    pub count: NvU32,
    pub entry: [NV2080_CTRL_FIFO_OBJSCHED_SW_GET_LOG_ENTRY; 200usize],
    pub schedPolicy: NvU32,
    pub arrEnabled: NvU32,
    pub arrAvgFactor: NvU32,
    pub targetTimesliceNs: NvU32,
}
impl Default for NV2080_CTRL_FIFO_OBJSCHED_SW_GET_LOG_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_FIFO_DEVICE_ENTRY {
    pub engineData: [NvU32; 16usize],
    pub pbdmaIds: [NvU32; 2usize],
    pub pbdmaFaultIds: [NvU32; 2usize],
    pub numPbdmas: NvU32,
    pub engineName: [::core::ffi::c_char; 16usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS {
    pub baseIndex: NvU32,
    pub numEntries: NvU32,
    pub bMore: NvBool,
    pub entries: [NV2080_CTRL_FIFO_DEVICE_ENTRY; 32usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_CMD_FIFO_ROTATE_KEYS_PARAMS {
    pub numChannels: NvU32,
    pub hClientList: [NvHandle; 64usize],
    pub hChannelList: [NvHandle; 64usize],
    pub bEnableAfterKeyRotation: NvBool,
}
impl Default for NV2080_CTRL_CMD_FIFO_ROTATE_KEYS_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV30F1_CTRL_GSYNC_GET_POSSIBLE_REFRESH_RATES_PARAMS {
    pub gpuId: NvU32,
    pub hTotal: NvU32,
    pub vTotal: NvU32,
    pub minRefreshRatex10000: NvU32,
    pub maxRefreshRatex10000: NvU32,
    pub numFractions: NvU32,
    pub fractions: [NV30F1_CTRL_GSYNC_GET_POSSIBLE_REFRESH_RATES_PARAMS__bindgen_ty_1; 5000usize],
}
impl Default for NV30F1_CTRL_GSYNC_GET_POSSIBLE_REFRESH_RATES_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV30F1_CTRL_GSYNC_GET_POSSIBLE_REFRESH_RATES_PARAMS__bindgen_ty_1 {
    pub numerator: NvU64,
    pub denominator: NvU64,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_DISPLAY_GET_STATIC_INFO_PARAMS {
    pub feHwSysCap: NvU32,
    pub windowPresentMask: NvU32,
    pub bFbRemapperEnabled: NvBool,
    pub numHeads: NvU32,
    pub i2cPort: NvU32,
    pub internalDispActiveMask: NvU32,
    pub embeddedDisplayPortMask: NvU32,
    pub bExternalMuxSupported: NvBool,
    pub bInternalMuxSupported: NvBool,
    pub numDispChannels: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_GR_GLOBAL_SM_ORDER {
    pub globalSmId: [NV2080_CTRL_INTERNAL_STATIC_GR_GLOBAL_SM_ORDER__bindgen_ty_1; 240usize],
    pub numSm: NvU16,
    pub numTpc: NvU16,
}
impl Default for NV2080_CTRL_INTERNAL_STATIC_GR_GLOBAL_SM_ORDER {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_GR_GLOBAL_SM_ORDER__bindgen_ty_1 {
    pub gpcId: NvU16,
    pub localTpcId: NvU16,
    pub localSmId: NvU16,
    pub globalTpcId: NvU16,
    pub virtualGpcId: NvU16,
    pub migratableTpcId: NvU16,
    pub ugpuId: NvU16,
    pub physicalCpcId: NvU16,
    pub virtualTpcId: NvU16,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_GR_GET_GLOBAL_SM_ORDER_PARAMS {
    pub globalSmOrder: [NV2080_CTRL_INTERNAL_STATIC_GR_GLOBAL_SM_ORDER; 8usize],
}
impl Default for NV2080_CTRL_INTERNAL_STATIC_GR_GET_GLOBAL_SM_ORDER_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
pub type NV2080_CTRL_INTERNAL_STATIC_KGR_GET_GLOBAL_SM_ORDER_PARAMS =
    NV2080_CTRL_INTERNAL_STATIC_GR_GET_GLOBAL_SM_ORDER_PARAMS;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_BSP_CAPS {
    pub capsTbl: [NvU8; 8usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_BSP_GET_CAPS_PARAMS {
    pub caps: [NV2080_CTRL_INTERNAL_BSP_CAPS; 8usize],
    pub valid: [NvBool; 8usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_MSENC_CAPS {
    pub capsTbl: [NvU8; 6usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_MSENC_GET_CAPS_PARAMS {
    pub caps: [NV2080_CTRL_INTERNAL_MSENC_CAPS; 8usize],
    pub valid: [NvBool; 8usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_GR_FLOORSWEEPING_MASKS {
    pub gpcMask: NvU32,
    pub tpcMask: [NvU32; 32usize],
    pub tpcCount: [NvU32; 32usize],
    pub physGpcMask: NvU32,
    pub mmuPerGpc: [NvU32; 32usize],
    pub tpcToPesMap: [NvU32; 10usize],
    pub numPesPerGpc: [NvU32; 32usize],
    pub zcullMask: [NvU32; 32usize],
    pub physGfxGpcMask: NvU32,
    pub numGfxTpc: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_GR_GET_FLOORSWEEPING_MASKS_PARAMS {
    pub floorsweepingMasks: [NV2080_CTRL_INTERNAL_STATIC_GR_FLOORSWEEPING_MASKS; 8usize],
}
/// Layout verified for: 595.99.02
pub type NV2080_CTRL_INTERNAL_STATIC_KGR_GET_FLOORSWEEPING_MASKS_PARAMS =
    NV2080_CTRL_INTERNAL_STATIC_GR_GET_FLOORSWEEPING_MASKS_PARAMS;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_GR_INFO {
    pub infoList: [NV2080_CTRL_INTERNAL_GR_INFO; 59usize],
}
impl Default for NV2080_CTRL_INTERNAL_STATIC_GR_INFO {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_GR_GET_INFO_PARAMS {
    pub engineInfo: [NV2080_CTRL_INTERNAL_STATIC_GR_INFO; 8usize],
}
impl Default for NV2080_CTRL_INTERNAL_STATIC_GR_GET_INFO_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
pub type NV2080_CTRL_INTERNAL_STATIC_KGR_GET_INFO_PARAMS =
    NV2080_CTRL_INTERNAL_STATIC_GR_GET_INFO_PARAMS;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_GR_PPC_MASKS {
    pub mask: [NvU32; 32usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_GR_GET_PPC_MASKS_PARAMS {
    pub enginePpcMasks: [NV2080_CTRL_INTERNAL_STATIC_GR_PPC_MASKS; 8usize],
}
/// Layout verified for: 595.99.02
pub type NV2080_CTRL_INTERNAL_STATIC_KGR_GET_PPC_MASKS_PARAMS =
    NV2080_CTRL_INTERNAL_STATIC_GR_GET_PPC_MASKS_PARAMS;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_GPU_GET_CHIP_INFO_PARAMS {
    pub chipSubRev: NvU8,
    pub emulationRev1: NvU32,
    pub isCmpSku: NvBool,
    pub pciDeviceId: NvU32,
    pub pciSubDeviceId: NvU32,
    pub pciRevisionId: NvU32,
    pub regBases: [NvU32; 16usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_GPU_GET_USER_REGISTER_ACCESS_MAP_PARAMS {
    pub userRegisterAccessMapSize: NvU32,
    pub compressedSize: NvU32,
    pub compressedData: [NvU8; 4096usize],
    pub profilingRangesSize: NvU32,
    pub profilingRanges: [NvU8; 4096usize],
}
impl Default for NV2080_CTRL_INTERNAL_GPU_GET_USER_REGISTER_ACCESS_MAP_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_GRMGR_SKYLINE_INFO {
    pub skylineVgpcSize: [NvU8; 32usize],
    pub singletonVgpcMask: NvU32,
    pub maxInstances: NvU32,
    pub computeSizeFlag: NvU32,
    pub numNonSingletonVgpcs: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_GRMGR_GET_SKYLINE_INFO_PARAMS {
    pub skylineTable: [NV2080_CTRL_INTERNAL_GRMGR_SKYLINE_INFO; 9usize],
    pub validEntries: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_GET_PCIE_P2P_CAPS_PARAMS {
    pub bCommonPciSwitchFound: NvBool,
    pub p2pReadCapsStatus: NvU8,
    pub p2pWriteCapsStatus: NvU8,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_MIGMGR_COMPUTE_PROFILE {
    pub computeSize: NvU8,
    pub gfxGpcCount: NvU32,
    pub gpcCount: NvU32,
    pub veidCount: NvU32,
    pub smCount: NvU32,
    pub physicalSlots: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_STATIC_MIGMGR_GET_COMPUTE_PROFILES_PARAMS {
    pub profileCount: NvU32,
    pub profiles: [NV2080_CTRL_INTERNAL_MIGMGR_COMPUTE_PROFILE; 8usize],
}
/// Layout verified for: 595.99.02
pub type NV2080_CTRL_INTERNAL_STATIC_KMIGMGR_GET_COMPUTE_PROFILES_PARAMS =
    NV2080_CTRL_INTERNAL_STATIC_MIGMGR_GET_COMPUTE_PROFILES_PARAMS;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_INIT_BRIGHTC_STATE_LOAD_PARAMS {
    pub status: NvU32,
    pub backLightDataSize: NvU16,
    pub backLightData: [NvU8; 4096usize],
}
impl Default for NV2080_CTRL_INTERNAL_INIT_BRIGHTC_STATE_LOAD_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_INTERNAL_START_GPU_FABRIC_PROBE_INFO_PARAMS {
    pub bwMode: NvU16,
    pub bLocalEgmEnabled: NvBool,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_INTERNAL_RESUME_GPU_FABRIC_PROBE_INFO_PARAMS {
    pub bwMode: NvU16,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_USER_SHARED_DATA_SET_DATA_POLL_PARAMS {
    pub polledDataMask: NvU64,
    pub pollIntervalMs: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_INTERNAL_CONTROL_GSP_TRACE_PARAMS {
    pub tracepointMask: NvU64,
    pub bufferAddr: NvU64,
    pub bufferSize: NvU32,
    pub bufferWatermark: NvU32,
    pub flag: NvU8,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_NVLINK_SAVE_RESTORE_HSHUB_STATE_PARAMS {
    pub bSave: NvBool,
    pub linkMask: NV2080_CTRL_NVLINK_LINK_MASK,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_NVLINK_LINK_TRAIN_ALI_PARAMS {
    pub linkMask: NvU32,
    pub bSync: NvBool,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_NVLINK_GET_NVLINK_DEVICE_INFO_PARAMS {
    pub ioctrlMask: NvU32,
    pub ioctrlNumEntries: NvU8,
    pub ioctrlSize: NvU32,
    pub discoveredLinks: NV2080_CTRL_NVLINK_LINK_MASK,
    pub ipVerNvlink: NvU32,
    pub maxSupportedLinks: NvU32,
    pub linkInfo: [NV2080_CTRL_INTERNAL_NVLINK_DEVICE_LINK_VALUES; 64usize],
}
impl Default for NV2080_CTRL_INTERNAL_NVLINK_GET_NVLINK_DEVICE_INFO_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_NVLINK_ARE_LINKS_TRAINED_PARAMS {
    pub linkMask: NV2080_CTRL_NVLINK_LINK_MASK,
    pub bActiveOnly: NvBool,
    pub bIsLinkActive: [NvBool; 64usize],
}
impl Default for NV2080_CTRL_INTERNAL_NVLINK_ARE_LINKS_TRAINED_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_NVLINK_GET_LINK_AND_CLOCK_VALUES {
    pub bLinkConnectedToSystem: NvBool,
    pub bLinkConnectedToPeer: NvBool,
    pub bLinkReset: NvBool,
    pub subLinkWidth: NvU8,
    pub linkState: NvU32,
    pub txSublinkState: NvU32,
    pub rxSublinkState: NvU32,
    pub bLaneReversal: NvBool,
    pub nvlinkLinkClockKHz: NvU32,
    pub nvlinkLineRateMbps: NvU32,
    pub nvlinkLinkClockMhz: NvU32,
    pub nvlinkLinkDataRateKiBps: NvU32,
    pub nvlinkRefClkType: NvU8,
    pub nvlinkReqLinkClockMhz: NvU32,
    pub nvlinkMinL1Threshold: NvU32,
    pub nvlinkMaxL1Threshold: NvU32,
    pub nvlinkL1ThresholdUnits: NvU32,
    pub nvlpwIdx: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_NVLINK_GET_LINK_AND_CLOCK_INFO_PARAMS {
    pub linkMask: NvU64,
    pub links: NV2080_CTRL_NVLINK_LINK_MASK,
    pub enabledNvlpwMask: NvU64,
    pub nvlinkRefClkSpeedKHz: NvU32,
    pub bSublinkStateInst: NvBool,
    pub linkInfo: [NV2080_CTRL_INTERNAL_NVLINK_GET_LINK_AND_CLOCK_VALUES; 64usize],
}
impl Default for NV2080_CTRL_INTERNAL_NVLINK_GET_LINK_AND_CLOCK_INFO_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_SEND_CMC_UMD_API_OP_PARAMS {
    pub opType: NvU32,
    pub flags: NvU32,
    pub ringBufferSize: NvU32,
    pub ringBufferOffset: NvU64,
    pub userdPa: NvU64,
    pub userdVa: NvU64,
    pub usermodeGpuVa: NvU64,
    pub instBlkAddr: NvU64,
    pub instBlkAperture: NvU8,
    pub userdAperture: NvU8,
    pub inputWorkSubmitToken: NvU32,
    pub cmcWorkSubmitToken: NvU32,
    pub cmcHandle: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_FLCN_SET_VIDEO_EVENT_BUFFER_MEMORY_PARAMS {
    pub memDescInfo: NV2080_CTRL_INTERNAL_MEMDESC_INFO,
    pub engDesc: NvU32,
    pub bEngineFound: NvBool,
}
/// Layout verified for: 595.99.02
pub type NV2080_CTRL_CMD_INTERNAL_CONF_COMPUTE_ROTATE_PER_CHANNEL_KEYS_PARAMS =
    NV2080_CTRL_CMD_FIFO_ROTATE_KEYS_PARAMS;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_INTERNAL_GSYNC_GET_POSSIBLE_REFRESH_RATES_PARAMS {
    pub params: NV30F1_CTRL_GSYNC_GET_POSSIBLE_REFRESH_RATES_PARAMS,
}
impl Default for NV2080_CTRL_INTERNAL_GSYNC_GET_POSSIBLE_REFRESH_RATES_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_BUS_GET_C2C_INFO_PARAMS {
    pub bIsLinkUp: NvBool,
    pub bLinkInHS: NvBool,
    pub nrLinks: NvU32,
    pub maxNrLinks: NvU32,
    pub linkMask: NvU32,
    pub perLinkBwMBps: NvU32,
    pub perLinkLaneWidth: NvU32,
    pub remoteType: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_BUS_GET_C2C_LPWR_STATS_PARAMS {
    pub c2cStateSupportMask: NvU32,
    pub bCl3Support: NvBool,
    pub cl3EntryCount: NvU32,
    pub cl3ExitCount: NvU32,
    pub cl3ResidentTimeUs: NvU32,
    pub cl3AvgEntryLatencyUs: NvU32,
    pub cl3AvgExitLatencyUs: NvU32,
    pub cl3PstateSupportMask: NvU32,
    pub cl3DisallowReasonMask: NvU32,
    pub bCl4Support: NvBool,
    pub cl4EntryCount: NvU32,
    pub cl4ExitCount: NvU32,
    pub cl4ResidentTimeUs: NvU32,
    pub cl4AvgEntryLatencyUs: NvU32,
    pub cl4AvgExitLatencyUs: NvU32,
    pub cl4PstateSupportMask: NvU32,
    pub cl4DisallowReasonMask: NvU32,
    pub c2cLpwrStateAllowedMask: NvU32,
    pub localPowerState: NvU32,
    pub remotePowerState: NvU32,
    pub cl3IdleThresholdUs: NvU32,
    pub cl4IdleThresholdUs: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_BUS_SET_C2C_LPWR_IDLE_THRESHOLD_PARAMS {
    pub c2cLpwrStateId: NvU32,
    pub idleThresholdUs: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_BUS_GET_C2C_PACKET_COUNTERS_PARAMS {
    pub packetCounters: [NvU32; 14usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV0000_CTRL_GPU_DISABLE_NVLINK_INIT_PARAMS {
    pub gpuId: NvU32,
    pub mask: NvU32,
    pub links: NV0000_CTRL_NVLINK_LINK_MASK,
    pub bSkipHwNvlinkDisable: NvBool,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV0000_CTRL_GPU_SET_NVLINK_BW_MODE_PARAMS {
    pub mode: NvU8,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV0000_CTRL_GPU_PCI_READ_WRITE_PARAMS {
    pub bWrite: NvBool,
    pub pciDomain: NvU16,
    pub pciBus: NvU8,
    pub pciDevice: NvU8,
    pub pciFunction: NvU8,
    pub pciOffset: NvU8,
    pub dataSize: NvU32,
    pub data: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV0080_CTRL_FB_GET_COMPBIT_STORE_INFO_PARAMS {
    pub Size: NvU64,
    pub Address: NvU64,
    pub AddressSpace: NvU32,
    pub MaxCompbitLine: NvU32,
    pub comptagsPerCacheLine: NvU32,
    pub cacheLineSize: NvU32,
    pub cacheLineSizePerSlice: NvU32,
    pub cacheLineFetchAlignment: NvU32,
    pub backingStoreBase: NvU64,
    pub gobsPerComptagPerSlice: NvU32,
    pub backingStoreCbcBase: NvU32,
    pub comptaglineAllocationPolicy: NvU32,
    pub privRegionStartOffset: NvU64,
    pub cbcCoveragePerSlice: NvU32,
    pub cbcRegionSize: NvU64,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_FB_GET_FB_REGION_FB_REGION_INFO {
    pub base: NvU64,
    pub limit: NvU64,
    pub reserved: NvU64,
    pub performance: NvU32,
    pub supportCompressed: NvBool,
    pub supportISO: NvBool,
    pub bProtected: NvBool,
    pub blackList: [NvBool; 18usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_FB_GET_FB_REGION_INFO_PARAMS {
    pub numFBRegions: NvU32,
    pub fbRegion: [NV2080_CTRL_CMD_FB_GET_FB_REGION_FB_REGION_INFO; 16usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_FB_ROW_REMAP_ENTRY {
    pub remapRegVal: NvU32,
    pub timestamp: NvU32,
    pub fbpa: NvU8,
    pub sublocation: NvU8,
    pub source: NvU8,
    pub flags: NvU8,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_FB_GET_REMAPPED_ROWS_PARAMS {
    pub entryCount: NvU32,
    pub flags: NvU8,
    pub entries: [NV2080_CTRL_FB_ROW_REMAP_ENTRY; 512usize],
}
impl Default for NV2080_CTRL_FB_GET_REMAPPED_ROWS_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_CMD_FB_STATS_ENTRY {
    pub totalSize: NvU64,
    pub rsvdSize: NvU64,
    pub osSize: NvU64,
    pub r1Size: NvU64,
    pub r2Size: NvU64,
    pub freeSize: NvU64,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_CMD_FB_STATS_GET_PARAMS {
    pub version: NvU64,
    pub fbSizeInfo: NV2080_CTRL_CMD_FB_STATS_ENTRY,
    pub fbBlockInfo: [NV2080_CTRL_CMD_FB_STATS_OWNER_INFO; 200usize],
}
impl Default for NV2080_CTRL_CMD_FB_STATS_GET_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_FB_BANK_REMAP_HISTOGRAM {
    pub maxGroupCount: NvU32,
    pub noSpareGroupCount: NvU32,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_FB_BANK_REMAP_ENTRY {
    pub remapRegVal: NvU32,
    pub timestamp: NvU32,
    pub fbpa: NvU8,
    pub channel: NvU8,
    pub pseudoChannel: NvU8,
    pub group: NvU8,
    pub source: NvU8,
    pub flags: NvU8,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NV2080_CTRL_FB_GET_REMAPPED_BANKS_PARAMS {
    pub entryCount: NvU32,
    pub flags: NvU8,
    pub histogram: NV2080_CTRL_FB_BANK_REMAP_HISTOGRAM,
    pub entries: [NV2080_CTRL_FB_BANK_REMAP_ENTRY; 512usize],
}
impl Default for NV2080_CTRL_FB_GET_REMAPPED_BANKS_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NV2080_CTRL_FB_GET_UGPU_MEMORY_INFO_PARAMS {
    pub totalMemory: NvU64,
    pub freeMemory: NvU64,
    pub ugpuTotalMemory: [NvU64; 2usize],
    pub ugpuFreeMemory: [NvU64; 2usize],
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UvmPmaStatistics_tag {
    pub numPages2m: NvU64,
    pub numFreePages64k: NvU64,
    pub numFreePages2m: NvU64,
    pub numPages2mProtected: NvU64,
    pub numFreePages64kProtected: NvU64,
    pub numFreePages2mProtected: NvU64,
    pub numPages2mLocalizable: [NvU64; 2usize],
    pub numFreePages64kLocalizable: [NvU64; 2usize],
    pub numFreePages2mLocalizable: [NvU64; 2usize],
}
/// Layout verified for: 595.99.02
pub type UvmPmaStatistics = UvmPmaStatistics_tag;
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_ADD_SESSION_PARAMS {
    pub pidTarget: NvU32,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_ENABLE_COUNTERS_PARAMS {
    pub config: [UvmCounterConfig; 32usize],
    pub count: NvU32,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UVM_MAP_COUNTER_PARAMS {
    pub scope: NvU32,
    pub counterName: NvU32,
    pub gpuUuid: NvProcessorUuid,
    pub addr: NvP64,
    pub rmStatus: NV_STATUS,
}
impl Default for UVM_MAP_COUNTER_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_CREATE_EVENT_QUEUE_PARAMS {
    pub eventQueueIndex: NvU32,
    pub queueSize: NvU64,
    pub notificationCount: NvU64,
    pub notificationHandle: NvU64,
    pub timeStampType: NvU32,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_REMOVE_EVENT_QUEUE_PARAMS {
    pub eventQueueIndex: NvU32,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UVM_MAP_EVENT_QUEUE_PARAMS {
    pub eventQueueIndex: NvU32,
    pub userRODataAddr: NvP64,
    pub userRWDataAddr: NvP64,
    pub readIndexAddr: NvP64,
    pub writeIndexAddr: NvP64,
    pub queueBufferAddr: NvP64,
    pub rmStatus: NV_STATUS,
}
impl Default for UVM_MAP_EVENT_QUEUE_PARAMS {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_EVENT_CTRL_PARAMS {
    pub eventQueueIndex: NvU32,
    pub eventType: NvS32,
    pub enable: NvU32,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_CREATE_RANGE_GROUP_PARAMS {
    pub rangeGroupId: NvU64,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_DESTROY_RANGE_GROUP_PARAMS {
    pub rangeGroupId: NvU64,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_UNREGISTER_CHANNEL_PARAMS {
    pub hClient: NvHandle,
    pub hChannel: NvHandle,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_SET_RANGE_GROUP_PARAMS {
    pub rangeGroupId: NvU64,
    pub requestedBase: NvU64,
    pub length: NvU64,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_FREE_PARAMS {
    pub base: NvU64,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_PREVENT_MIGRATION_RANGE_GROUPS_PARAMS {
    pub rangeGroupIds: [NvU64; 32usize],
    pub numGroupIds: NvU64,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_ALLOW_MIGRATION_RANGE_GROUPS_PARAMS {
    pub rangeGroupIds: [NvU64; 32usize],
    pub numGroupIds: NvU64,
    pub rmStatus: NV_STATUS,
}
/// Layout verified for: 595.99.02
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct UVM_MIGRATE_RANGE_GROUP_PARAMS {
    pub rangeGroupId: NvU64,
    pub destinationUuid: NvProcessorUuid,
    pub rmStatus: NV_STATUS,
}

// The measured layout. Every number below is read out of the manifest
// beside this crate, which was read out of bindgen's own layout assertions
// for this driver version's headers. A mismatch here means the committed
// source and the committed evidence have come apart.
assert_layout!(offline_addresses, size = 520, align = 8,
    addresses @ 0,
    numEntries @ 512);
assert_layout!(nv_ioctl_numa_info, size = 560, align = 8,
    nid @ 0,
    status @ 4,
    memblock_size @ 8,
    numa_mem_addr @ 16,
    numa_mem_size @ 24,
    use_auto_online @ 32,
    offline_addresses @ 40);
assert_layout!(nv_ioctl_set_numa_status, size = 4, align = 4,
    status @ 0);
assert_layout!(NV_CHANNEL_ALLOC_PARAMS, size = 368, align = 8,
    hObjectError @ 0,
    hObjectBuffer @ 4,
    gpFifoOffset @ 8,
    gpFifoEntries @ 16,
    flags @ 20,
    hContextShare @ 24,
    hVASpace @ 28,
    hUserdMemory @ 32,
    userdOffset @ 64,
    engineType @ 128,
    cid @ 132,
    subDeviceId @ 136,
    hObjectEccError @ 140,
    instanceMem @ 144,
    userdMem @ 168,
    ramfcMem @ 192,
    mthdbufMem @ 216,
    hPhysChannelGroup @ 240,
    internalFlags @ 244,
    errorNotifierMem @ 248,
    eccErrorNotifierMem @ 272,
    ProcessID @ 296,
    SubProcessID @ 300,
    encryptIv @ 304,
    decryptIv @ 316,
    hmacNonce @ 328,
    tpcConfigID @ 360);
assert_layout!(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, size = 20, align = 4,
    hObjectError @ 0,
    hObjectEccError @ 4,
    hVASpace @ 8,
    engineType @ 12,
    bIsCallingContextVgpuPlugin @ 16);
assert_layout!(NV2080_CTRL_ECC_INJECTION_SUPPORTED_PARAMS, size = 8, align = 4,
    unit @ 0,
    bCorrectableSupported @ 4,
    bUncorrectableSupported @ 5);
assert_layout!(NVA083_CTRL_VIRTUAL_DISPLAY_GET_NUM_HEADS_PARAMS, size = 8, align = 4,
    numHeads @ 0,
    maxNumHeads @ 4);
assert_layout!(NVA083_CTRL_VIRTUAL_DISPLAY_GET_MAX_RESOLUTION_PARAMS, size = 12, align = 4,
    headIndex @ 0,
    maxHResolution @ 4,
    maxVResolution @ 8);
assert_layout!(NVA083_CTRL_VIRTUAL_DISPLAY_GET_DEFAULT_EDID_PARAMS, size = 16, align = 8,
    pEdidBuffer @ 0,
    edidSize @ 8,
    connectorType @ 12);
assert_layout!(NVA083_CTRL_VIRTUAL_DISPLAY_IS_ACTIVE_PARAMS, size = 1, align = 1,
    isDisplayActive @ 0);
assert_layout!(NVA083_CTRL_VIRTUAL_DISPLAY_IS_CONNECTED_PARAMS, size = 4, align = 4,
    isDisplayConnected @ 0);
assert_layout!(NVA083_CTRL_VIRTUAL_DISPLAY_GET_MAX_PIXELS_PARAMS, size = 8, align = 8,
    maxPixels @ 0);
assert_layout!(NV0080_CTRL_GR_GET_INFO_V2_PARAMS, size = 496, align = 8,
    grInfoListSize @ 0,
    grInfoList @ 4,
    grRouteInfo @ 480);
assert_layout!(NV2080_CTRL_GR_GET_SM_TO_GPC_TPC_MAPPINGS_PARAMS, size = 1944, align = 8,
    smId @ 0,
    smCount @ 1920,
    grRouteInfo @ 1928);
assert_layout!(NV2080_CTRL_GR_GET_GLOBAL_SM_ORDER_PARAMS, size = 9240, align = 8,
    globalSmId @ 0,
    numSm @ 9216,
    numTpc @ 9218,
    grRouteInfo @ 9224);
assert_layout!(NV2080_CTRL_GR_GET_GLOBAL_SM_ORDER_PARAMS__bindgen_ty_1, size = 18, align = 2,
    gpcId @ 0,
    localTpcId @ 2,
    localSmId @ 4,
    globalTpcId @ 6,
    virtualGpcId @ 8,
    migratableTpcId @ 10,
    ugpuId @ 12,
    physicalCpcId @ 14,
    virtualTpcId @ 16);
assert_layout!(NV2080_CTRL_GR_TEST_CTXSW_ERROR_LOGS_PARAMS, size = 8, align = 4,
    expectedCharCount @ 0,
    bUseInterrupt @ 4);
assert_layout!(NV0000_CTRL_SYSTEM_GET_CHIPSET_INFO_PARAMS, size = 152, align = 4,
    vendorId @ 0,
    deviceId @ 2,
    subSysVendorId @ 4,
    subSysDeviceId @ 6,
    HBvendorId @ 8,
    HBdeviceId @ 10,
    HBsubSysVendorId @ 12,
    HBsubSysDeviceId @ 14,
    sliBondId @ 16,
    vendorNameString @ 20,
    subSysVendorNameString @ 52,
    chipsetNameString @ 84,
    sliBondNameString @ 116,
    flags @ 148);
assert_layout!(NV0000_CTRL_SYSTEM_GET_P2P_CAPS_MATRIX_PARAMS, size = 1352, align = 4,
    grpACount @ 0,
    grpBCount @ 4,
    gpuIdGrpA @ 8,
    gpuIdGrpB @ 40,
    p2pCaps @ 72,
    a2bOptimalReadCes @ 328,
    a2bOptimalWriteCes @ 584,
    b2aOptimalReadCes @ 840,
    b2aOptimalWriteCes @ 1096);
assert_layout!(NV0000_CTRL_SYSTEM_NVPCF_GET_POWER_MODE_INFO_PARAMS, size = 884, align = 4,
    supportedFuncs @ 0,
    gpuId @ 4,
    tpp @ 8,
    ratedTgp @ 12,
    subFunc @ 16,
    ctgpOffsetmW @ 20,
    targetTppOffsetmW @ 24,
    maxOutputOffsetmW @ 28,
    minOutputOffsetmW @ 32,
    ctgpBattOffsetmW @ 36,
    targetTppBattOffsetmW @ 40,
    maxOutputBattOffsetmW @ 44,
    minOutputBattOffsetmW @ 48,
    dcRosReserveOverridemW @ 52,
    dcTspLongTimescaleLimitmA @ 56,
    dcTspLongTimescaleLimitOverridemA @ 60,
    dcTspShortTimescaleLimitmA @ 64,
    dcTspShortTimescaleLimitOverridemA @ 68,
    bEnableForAC @ 72,
    bEnableForDC @ 73,
    version @ 74,
    samplingPeriodmS @ 76,
    samplingMulti @ 78,
    filterType @ 80,
    filterParam @ 81,
    filterReserved @ 82,
    bIsBoostController @ 84,
    incRatio @ 86,
    decRatio @ 88,
    bSupportBatt @ 90,
    cpuType @ 91,
    gpuType @ 92,
    sysPwrIndex @ 96,
    sysPwrGetInfo @ 100,
    bIsTspSupported @ 868,
    sysPwrLimitsTableVersion @ 869,
    type_ @ 872,
    cpuTdpmw @ 876,
    cpuTdpControlType @ 880);
assert_layout!(NV2080_CTRL_GPU_GET_INFO_V2_PARAMS, size = 564, align = 4,
    gpuInfoListSize @ 0,
    gpuInfoList @ 4);
assert_layout!(NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS, size = 68, align = 4,
    gpuNameStringFlags @ 0,
    gpuNameString @ 4);
assert_layout!(NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS__bindgen_ty_1, size = 64, align = 1,
    ascii @ 0);
assert_layout!(NV2080_CTRL_GPU_QUERY_ECC_STATUS_PARAMS, size = 1664, align = 8,
    units @ 0,
    bFatalPoisonError @ 1640,
    uncorrectableError @ 1641,
    flags @ 1644,
    grRouteInfo @ 1648);
assert_layout!(NV2080_CTRL_GPU_GET_PES_INFO_PARAMS, size = 56, align = 4,
    gpcId @ 0,
    numPesInGpc @ 4,
    activePesMask @ 8,
    maxTpcPerGpcCount @ 12,
    tpcToPesMap @ 16);
assert_layout!(NV2080_CTRL_GPU_GET_ENGINE_LOAD_TIMES_PARAMS, size = 2608, align = 8,
    engineCount @ 0,
    engineList @ 4,
    engineStateLoadTime @ 808,
    engineIsInit @ 2408);
assert_layout!(NV2080_CTRL_GPU_GET_ID_NAME_MAPPING_PARAMS, size = 20804, align = 4,
    engineCount @ 0,
    engineID @ 4,
    engineName @ 804);
assert_layout!(NV2080_CTRL_GPU_SKYLINE_INFO, size = 44, align = 4,
    skylineVgpcSize @ 0,
    singletonVgpcMask @ 32,
    maxInstances @ 36,
    computeSizeFlag @ 40);
assert_layout!(NV2080_CTRL_GPU_GET_SKYLINE_INFO_PARAMS, size = 400, align = 4,
    skylineTable @ 0,
    validEntries @ 396);
assert_layout!(NV2080_CTRL_GPU_COMPUTE_PROFILE, size = 20, align = 4,
    computeSize @ 0,
    gfxGpcCount @ 4,
    gpcCount @ 8,
    veidCount @ 12,
    smCount @ 16);
assert_layout!(NV2080_CTRL_GPU_GET_COMPUTE_PROFILES_PARAMS, size = 168, align = 4,
    partitionFlag @ 0,
    profileCount @ 4,
    profiles @ 8);
assert_layout!(NV2080_CTRL_CMD_GET_GPU_FABRIC_PROBE_INFO_PARAMS, size = 56, align = 8,
    state @ 0,
    status @ 4,
    clusterUuid @ 8,
    fabricPartitionId @ 24,
    fabricCaps @ 32,
    fabricCliqueId @ 40,
    fabricHealthMask @ 44,
    fabricHealthSummary @ 48);
assert_layout!(NV2080_CTRL_GPU_RUSD_SET_FEATURES_PARAMS, size = 8, align = 8,
    permanentPolledDataMask @ 0);
assert_layout!(NV2080_CTRL_GPU_VGA_SR_READ_WRITE_PARAMS, size = 12, align = 4,
    bWrite @ 0,
    head @ 4,
    index @ 8,
    data @ 9);
assert_layout!(NV2080_CTRL_GPU_ERROR_INJECTION_CONTROL_PARAMS, size = 4, align = 4,
    errorType @ 0);
assert_layout!(NV2080_CTRL_GPU_CHECK_MEM_SUBSYS_ERROR_PARAMS, size = 4, align = 4,
    flags @ 0);
assert_layout!(NV2080_CTRL_GPU_GET_DEFAULT_TIMEOUT_PARAMS, size = 4, align = 4,
    defaultTimeout @ 0);
assert_layout!(NV0080_CTRL_MSENC_GET_CAPS_V2_PARAMS, size = 12, align = 4,
    capsTbl @ 0,
    instanceId @ 8);
assert_layout!(NV0080_CTRL_BSP_GET_CAPS_PARAMS, size = 24, align = 8,
    capsTblSize @ 0,
    capsTbl @ 8,
    instanceId @ 16);
assert_layout!(NV0080_CTRL_BSP_GET_CAPS_PARAMS_V2, size = 12, align = 4,
    capsTbl @ 0,
    instanceId @ 8);
assert_layout!(NV2080_CTRL_FIFO_CHANNEL_PREEMPTIVE_REMOVAL_PARAMS, size = 4, align = 4,
    hChannel @ 0);
assert_layout!(NV2080_CTRL_FIFO_OBJSCHED_SW_GET_LOG_ENTRY, size = 120, align = 8,
    timestampNs @ 0,
    timeRunTotalNs @ 8,
    timeRunNs @ 16,
    swrlId @ 20,
    targetTimeSlice @ 24,
    cumulativePreemptionTime @ 32,
    cumulativeIdleTime @ 40,
    weight @ 48,
    counters @ 56);
assert_layout!(NV2080_CTRL_FIFO_OBJSCHED_SW_GET_LOG_PARAMS, size = 24024, align = 8,
    engineId @ 0,
    count @ 4,
    entry @ 8,
    schedPolicy @ 24008,
    arrEnabled @ 24012,
    arrAvgFactor @ 24016,
    targetTimesliceNs @ 24020);
assert_layout!(NV2080_CTRL_FIFO_DEVICE_ENTRY, size = 100, align = 4,
    engineData @ 0,
    pbdmaIds @ 64,
    pbdmaFaultIds @ 72,
    numPbdmas @ 80,
    engineName @ 84);
assert_layout!(NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS, size = 3212, align = 4,
    baseIndex @ 0,
    numEntries @ 4,
    bMore @ 8,
    entries @ 12);
assert_layout!(NV2080_CTRL_CMD_FIFO_ROTATE_KEYS_PARAMS, size = 520, align = 4,
    numChannels @ 0,
    hClientList @ 4,
    hChannelList @ 260,
    bEnableAfterKeyRotation @ 516);
assert_layout!(NV30F1_CTRL_GSYNC_GET_POSSIBLE_REFRESH_RATES_PARAMS, size = 80024, align = 8,
    gpuId @ 0,
    hTotal @ 4,
    vTotal @ 8,
    minRefreshRatex10000 @ 12,
    maxRefreshRatex10000 @ 16,
    numFractions @ 20,
    fractions @ 24);
assert_layout!(NV30F1_CTRL_GSYNC_GET_POSSIBLE_REFRESH_RATES_PARAMS__bindgen_ty_1, size = 16, align = 8,
    numerator @ 0,
    denominator @ 8);
assert_layout!(NV2080_CTRL_INTERNAL_DISPLAY_GET_STATIC_INFO_PARAMS, size = 36, align = 4,
    feHwSysCap @ 0,
    windowPresentMask @ 4,
    bFbRemapperEnabled @ 8,
    numHeads @ 12,
    i2cPort @ 16,
    internalDispActiveMask @ 20,
    embeddedDisplayPortMask @ 24,
    bExternalMuxSupported @ 28,
    bInternalMuxSupported @ 29,
    numDispChannels @ 32);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_GR_GLOBAL_SM_ORDER, size = 4324, align = 2,
    globalSmId @ 0,
    numSm @ 4320,
    numTpc @ 4322);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_GR_GLOBAL_SM_ORDER__bindgen_ty_1, size = 18, align = 2,
    gpcId @ 0,
    localTpcId @ 2,
    localSmId @ 4,
    globalTpcId @ 6,
    virtualGpcId @ 8,
    migratableTpcId @ 10,
    ugpuId @ 12,
    physicalCpcId @ 14,
    virtualTpcId @ 16);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_GR_GET_GLOBAL_SM_ORDER_PARAMS, size = 34592, align = 2,
    globalSmOrder @ 0);
assert_layout!(NV2080_CTRL_INTERNAL_BSP_CAPS, size = 8, align = 1,
    capsTbl @ 0);
assert_layout!(NV2080_CTRL_INTERNAL_BSP_GET_CAPS_PARAMS, size = 72, align = 1,
    caps @ 0,
    valid @ 64);
assert_layout!(NV2080_CTRL_INTERNAL_MSENC_CAPS, size = 6, align = 1,
    capsTbl @ 0);
assert_layout!(NV2080_CTRL_INTERNAL_MSENC_GET_CAPS_PARAMS, size = 56, align = 1,
    caps @ 0,
    valid @ 48);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_GR_FLOORSWEEPING_MASKS, size = 696, align = 4,
    gpcMask @ 0,
    tpcMask @ 4,
    tpcCount @ 132,
    physGpcMask @ 260,
    mmuPerGpc @ 264,
    tpcToPesMap @ 392,
    numPesPerGpc @ 432,
    zcullMask @ 560,
    physGfxGpcMask @ 688,
    numGfxTpc @ 692);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_GR_GET_FLOORSWEEPING_MASKS_PARAMS, size = 5568, align = 4,
    floorsweepingMasks @ 0);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_GR_INFO, size = 472, align = 4,
    infoList @ 0);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_GR_GET_INFO_PARAMS, size = 3776, align = 4,
    engineInfo @ 0);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_GR_PPC_MASKS, size = 128, align = 4,
    mask @ 0);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_GR_GET_PPC_MASKS_PARAMS, size = 1024, align = 4,
    enginePpcMasks @ 0);
assert_layout!(NV2080_CTRL_INTERNAL_GPU_GET_CHIP_INFO_PARAMS, size = 88, align = 4,
    chipSubRev @ 0,
    emulationRev1 @ 4,
    isCmpSku @ 8,
    pciDeviceId @ 12,
    pciSubDeviceId @ 16,
    pciRevisionId @ 20,
    regBases @ 24);
assert_layout!(NV2080_CTRL_INTERNAL_GPU_GET_USER_REGISTER_ACCESS_MAP_PARAMS, size = 8204, align = 4,
    userRegisterAccessMapSize @ 0,
    compressedSize @ 4,
    compressedData @ 8,
    profilingRangesSize @ 4104,
    profilingRanges @ 4108);
assert_layout!(NV2080_CTRL_INTERNAL_GRMGR_SKYLINE_INFO, size = 48, align = 4,
    skylineVgpcSize @ 0,
    singletonVgpcMask @ 32,
    maxInstances @ 36,
    computeSizeFlag @ 40,
    numNonSingletonVgpcs @ 44);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_GRMGR_GET_SKYLINE_INFO_PARAMS, size = 436, align = 4,
    skylineTable @ 0,
    validEntries @ 432);
assert_layout!(NV2080_CTRL_INTERNAL_GET_PCIE_P2P_CAPS_PARAMS, size = 3, align = 1,
    bCommonPciSwitchFound @ 0,
    p2pReadCapsStatus @ 1,
    p2pWriteCapsStatus @ 2);
assert_layout!(NV2080_CTRL_INTERNAL_MIGMGR_COMPUTE_PROFILE, size = 24, align = 4,
    computeSize @ 0,
    gfxGpcCount @ 4,
    gpcCount @ 8,
    veidCount @ 12,
    smCount @ 16,
    physicalSlots @ 20);
assert_layout!(NV2080_CTRL_INTERNAL_STATIC_MIGMGR_GET_COMPUTE_PROFILES_PARAMS, size = 196, align = 4,
    profileCount @ 0,
    profiles @ 4);
assert_layout!(NV2080_CTRL_INTERNAL_INIT_BRIGHTC_STATE_LOAD_PARAMS, size = 4104, align = 4,
    status @ 0,
    backLightDataSize @ 4,
    backLightData @ 6);
assert_layout!(NV2080_CTRL_CMD_INTERNAL_START_GPU_FABRIC_PROBE_INFO_PARAMS, size = 4, align = 2,
    bwMode @ 0,
    bLocalEgmEnabled @ 2);
assert_layout!(NV2080_CTRL_CMD_INTERNAL_RESUME_GPU_FABRIC_PROBE_INFO_PARAMS, size = 2, align = 2,
    bwMode @ 0);
assert_layout!(NV2080_CTRL_INTERNAL_USER_SHARED_DATA_SET_DATA_POLL_PARAMS, size = 16, align = 8,
    polledDataMask @ 0,
    pollIntervalMs @ 8);
assert_layout!(NV2080_CTRL_CMD_INTERNAL_CONTROL_GSP_TRACE_PARAMS, size = 32, align = 8,
    tracepointMask @ 0,
    bufferAddr @ 8,
    bufferSize @ 16,
    bufferWatermark @ 20,
    flag @ 24);
assert_layout!(NV2080_CTRL_INTERNAL_NVLINK_SAVE_RESTORE_HSHUB_STATE_PARAMS, size = 24, align = 8,
    bSave @ 0,
    linkMask @ 8);
assert_layout!(NV2080_CTRL_INTERNAL_NVLINK_LINK_TRAIN_ALI_PARAMS, size = 8, align = 4,
    linkMask @ 0,
    bSync @ 4);
assert_layout!(NV2080_CTRL_INTERNAL_NVLINK_GET_NVLINK_DEVICE_INFO_PARAMS, size = 1064, align = 8,
    ioctrlMask @ 0,
    ioctrlNumEntries @ 4,
    ioctrlSize @ 8,
    discoveredLinks @ 16,
    ipVerNvlink @ 32,
    maxSupportedLinks @ 36,
    linkInfo @ 40);
assert_layout!(NV2080_CTRL_INTERNAL_NVLINK_ARE_LINKS_TRAINED_PARAMS, size = 88, align = 8,
    linkMask @ 0,
    bActiveOnly @ 16,
    bIsLinkActive @ 17);
assert_layout!(NV2080_CTRL_INTERNAL_NVLINK_GET_LINK_AND_CLOCK_VALUES, size = 60, align = 4,
    bLinkConnectedToSystem @ 0,
    bLinkConnectedToPeer @ 1,
    bLinkReset @ 2,
    subLinkWidth @ 3,
    linkState @ 4,
    txSublinkState @ 8,
    rxSublinkState @ 12,
    bLaneReversal @ 16,
    nvlinkLinkClockKHz @ 20,
    nvlinkLineRateMbps @ 24,
    nvlinkLinkClockMhz @ 28,
    nvlinkLinkDataRateKiBps @ 32,
    nvlinkRefClkType @ 36,
    nvlinkReqLinkClockMhz @ 40,
    nvlinkMinL1Threshold @ 44,
    nvlinkMaxL1Threshold @ 48,
    nvlinkL1ThresholdUnits @ 52,
    nvlpwIdx @ 56);
assert_layout!(NV2080_CTRL_INTERNAL_NVLINK_GET_LINK_AND_CLOCK_INFO_PARAMS, size = 3880, align = 8,
    linkMask @ 0,
    links @ 8,
    enabledNvlpwMask @ 24,
    nvlinkRefClkSpeedKHz @ 32,
    bSublinkStateInst @ 36,
    linkInfo @ 40);
assert_layout!(NV2080_CTRL_INTERNAL_SEND_CMC_UMD_API_OP_PARAMS, size = 72, align = 8,
    opType @ 0,
    flags @ 4,
    ringBufferSize @ 8,
    ringBufferOffset @ 16,
    userdPa @ 24,
    userdVa @ 32,
    usermodeGpuVa @ 40,
    instBlkAddr @ 48,
    instBlkAperture @ 56,
    userdAperture @ 57,
    inputWorkSubmitToken @ 60,
    cmcWorkSubmitToken @ 64,
    cmcHandle @ 68);
assert_layout!(NV2080_CTRL_INTERNAL_FLCN_SET_VIDEO_EVENT_BUFFER_MEMORY_PARAMS, size = 40, align = 8,
    memDescInfo @ 0,
    engDesc @ 32,
    bEngineFound @ 36);
assert_layout!(NV2080_CTRL_INTERNAL_GSYNC_GET_POSSIBLE_REFRESH_RATES_PARAMS, size = 80024, align = 8,
    params @ 0);
assert_layout!(NV2080_CTRL_CMD_BUS_GET_C2C_INFO_PARAMS, size = 28, align = 4,
    bIsLinkUp @ 0,
    bLinkInHS @ 1,
    nrLinks @ 4,
    maxNrLinks @ 8,
    linkMask @ 12,
    perLinkBwMBps @ 16,
    perLinkLaneWidth @ 20,
    remoteType @ 24);
assert_layout!(NV2080_CTRL_CMD_BUS_GET_C2C_LPWR_STATS_PARAMS, size = 88, align = 4,
    c2cStateSupportMask @ 0,
    bCl3Support @ 4,
    cl3EntryCount @ 8,
    cl3ExitCount @ 12,
    cl3ResidentTimeUs @ 16,
    cl3AvgEntryLatencyUs @ 20,
    cl3AvgExitLatencyUs @ 24,
    cl3PstateSupportMask @ 28,
    cl3DisallowReasonMask @ 32,
    bCl4Support @ 36,
    cl4EntryCount @ 40,
    cl4ExitCount @ 44,
    cl4ResidentTimeUs @ 48,
    cl4AvgEntryLatencyUs @ 52,
    cl4AvgExitLatencyUs @ 56,
    cl4PstateSupportMask @ 60,
    cl4DisallowReasonMask @ 64,
    c2cLpwrStateAllowedMask @ 68,
    localPowerState @ 72,
    remotePowerState @ 76,
    cl3IdleThresholdUs @ 80,
    cl4IdleThresholdUs @ 84);
assert_layout!(NV2080_CTRL_CMD_BUS_SET_C2C_LPWR_IDLE_THRESHOLD_PARAMS, size = 8, align = 4,
    c2cLpwrStateId @ 0,
    idleThresholdUs @ 4);
assert_layout!(NV2080_CTRL_CMD_BUS_GET_C2C_PACKET_COUNTERS_PARAMS, size = 56, align = 4,
    packetCounters @ 0);
assert_layout!(NV0000_CTRL_GPU_DISABLE_NVLINK_INIT_PARAMS, size = 32, align = 8,
    gpuId @ 0,
    mask @ 4,
    links @ 8,
    bSkipHwNvlinkDisable @ 24);
assert_layout!(NV0000_CTRL_GPU_SET_NVLINK_BW_MODE_PARAMS, size = 1, align = 1,
    mode @ 0);
assert_layout!(NV0000_CTRL_GPU_PCI_READ_WRITE_PARAMS, size = 16, align = 4,
    bWrite @ 0,
    pciDomain @ 2,
    pciBus @ 4,
    pciDevice @ 5,
    pciFunction @ 6,
    pciOffset @ 7,
    dataSize @ 8,
    data @ 12);
assert_layout!(NV0080_CTRL_FB_GET_COMPBIT_STORE_INFO_PARAMS, size = 88, align = 8,
    Size @ 0,
    Address @ 8,
    AddressSpace @ 16,
    MaxCompbitLine @ 20,
    comptagsPerCacheLine @ 24,
    cacheLineSize @ 28,
    cacheLineSizePerSlice @ 32,
    cacheLineFetchAlignment @ 36,
    backingStoreBase @ 40,
    gobsPerComptagPerSlice @ 48,
    backingStoreCbcBase @ 52,
    comptaglineAllocationPolicy @ 56,
    privRegionStartOffset @ 64,
    cbcCoveragePerSlice @ 72,
    cbcRegionSize @ 80);
assert_layout!(NV2080_CTRL_CMD_FB_GET_FB_REGION_FB_REGION_INFO, size = 56, align = 8,
    base @ 0,
    limit @ 8,
    reserved @ 16,
    performance @ 24,
    supportCompressed @ 28,
    supportISO @ 29,
    bProtected @ 30,
    blackList @ 31);
assert_layout!(NV2080_CTRL_CMD_FB_GET_FB_REGION_INFO_PARAMS, size = 904, align = 8,
    numFBRegions @ 0,
    fbRegion @ 8);
assert_layout!(NV2080_CTRL_FB_ROW_REMAP_ENTRY, size = 12, align = 4,
    remapRegVal @ 0,
    timestamp @ 4,
    fbpa @ 8,
    sublocation @ 9,
    source @ 10,
    flags @ 11);
assert_layout!(NV2080_CTRL_FB_GET_REMAPPED_ROWS_PARAMS, size = 6152, align = 4,
    entryCount @ 0,
    flags @ 4,
    entries @ 8);
assert_layout!(NV2080_CTRL_CMD_FB_STATS_ENTRY, size = 48, align = 8,
    totalSize @ 0,
    rsvdSize @ 8,
    osSize @ 16,
    r1Size @ 24,
    r2Size @ 32,
    freeSize @ 40);
assert_layout!(NV2080_CTRL_CMD_FB_STATS_GET_PARAMS, size = 4856, align = 8,
    version @ 0,
    fbSizeInfo @ 8,
    fbBlockInfo @ 56);
assert_layout!(NV2080_CTRL_FB_BANK_REMAP_HISTOGRAM, size = 8, align = 4,
    maxGroupCount @ 0,
    noSpareGroupCount @ 4);
assert_layout!(NV2080_CTRL_FB_BANK_REMAP_ENTRY, size = 16, align = 4,
    remapRegVal @ 0,
    timestamp @ 4,
    fbpa @ 8,
    channel @ 9,
    pseudoChannel @ 10,
    group @ 11,
    source @ 12,
    flags @ 13);
assert_layout!(NV2080_CTRL_FB_GET_REMAPPED_BANKS_PARAMS, size = 8208, align = 4,
    entryCount @ 0,
    flags @ 4,
    histogram @ 8,
    entries @ 16);
assert_layout!(NV2080_CTRL_FB_GET_UGPU_MEMORY_INFO_PARAMS, size = 48, align = 8,
    totalMemory @ 0,
    freeMemory @ 8,
    ugpuTotalMemory @ 16,
    ugpuFreeMemory @ 32);
assert_layout!(UvmPmaStatistics_tag, size = 96, align = 8,
    numPages2m @ 0,
    numFreePages64k @ 8,
    numFreePages2m @ 16,
    numPages2mProtected @ 24,
    numFreePages64kProtected @ 32,
    numFreePages2mProtected @ 40,
    numPages2mLocalizable @ 48,
    numFreePages64kLocalizable @ 64,
    numFreePages2mLocalizable @ 80);
assert_layout!(UVM_ADD_SESSION_PARAMS, size = 8, align = 4,
    pidTarget @ 0,
    rmStatus @ 4);
assert_layout!(UVM_ENABLE_COUNTERS_PARAMS, size = 904, align = 4,
    config @ 0,
    count @ 896,
    rmStatus @ 900);
assert_layout!(UVM_MAP_COUNTER_PARAMS, size = 40, align = 8,
    scope @ 0,
    counterName @ 4,
    gpuUuid @ 8,
    addr @ 24,
    rmStatus @ 32);
assert_layout!(UVM_CREATE_EVENT_QUEUE_PARAMS, size = 40, align = 8,
    eventQueueIndex @ 0,
    queueSize @ 8,
    notificationCount @ 16,
    notificationHandle @ 24,
    timeStampType @ 32,
    rmStatus @ 36);
assert_layout!(UVM_REMOVE_EVENT_QUEUE_PARAMS, size = 8, align = 4,
    eventQueueIndex @ 0,
    rmStatus @ 4);
assert_layout!(UVM_MAP_EVENT_QUEUE_PARAMS, size = 56, align = 8,
    eventQueueIndex @ 0,
    userRODataAddr @ 8,
    userRWDataAddr @ 16,
    readIndexAddr @ 24,
    writeIndexAddr @ 32,
    queueBufferAddr @ 40,
    rmStatus @ 48);
assert_layout!(UVM_EVENT_CTRL_PARAMS, size = 16, align = 4,
    eventQueueIndex @ 0,
    eventType @ 4,
    enable @ 8,
    rmStatus @ 12);
assert_layout!(UVM_CREATE_RANGE_GROUP_PARAMS, size = 16, align = 8,
    rangeGroupId @ 0,
    rmStatus @ 8);
assert_layout!(UVM_DESTROY_RANGE_GROUP_PARAMS, size = 16, align = 8,
    rangeGroupId @ 0,
    rmStatus @ 8);
assert_layout!(UVM_UNREGISTER_CHANNEL_PARAMS, size = 12, align = 4,
    hClient @ 0,
    hChannel @ 4,
    rmStatus @ 8);
assert_layout!(UVM_SET_RANGE_GROUP_PARAMS, size = 32, align = 8,
    rangeGroupId @ 0,
    requestedBase @ 8,
    length @ 16,
    rmStatus @ 24);
assert_layout!(UVM_FREE_PARAMS, size = 16, align = 8,
    base @ 0,
    rmStatus @ 8);
assert_layout!(UVM_PREVENT_MIGRATION_RANGE_GROUPS_PARAMS, size = 272, align = 8,
    rangeGroupIds @ 0,
    numGroupIds @ 256,
    rmStatus @ 264);
assert_layout!(UVM_ALLOW_MIGRATION_RANGE_GROUPS_PARAMS, size = 272, align = 8,
    rangeGroupIds @ 0,
    numGroupIds @ 256,
    rmStatus @ 264);
assert_layout!(UVM_MIGRATE_RANGE_GROUP_PARAMS, size = 32, align = 8,
    rangeGroupId @ 0,
    destinationUuid @ 8,
    rmStatus @ 24);
