#!/bin/sh
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Silas Müller <github@silasmueller.de>
# SPDX-FileCopyrightText: 2026 Universität Stuttgart, IKR
set -e
if [ "$1" = remove ] || [ "$1" = upgrade ]; then
    systemctl disable leandro-nvrm.service leandro-display.service || true
    dkms remove -m leandro-guest -v @VERSION@ --all || true
fi
