# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Silas Müller <github@silasmueller.de>
# SPDX-FileCopyrightText: 2026 Universität Stuttgart, IKR
# The per-library ioctl coverage matrix: everything that is shared between
# the entry point (scripts/ioctl-matrix.sh) and the probes in probe/matrix/.
# Not a script -- source it:
#   source "$LEA_ROOT/scripts/lib/matrix.sh"
#
# THE RULE THIS FILE EXISTS TO ENFORCE: nothing here is a list of NVIDIA
# facts. Every number, every library name and every command name is READ --
# from the running driver, from the host's package manager, from
# scripts/lib/provision.sh's own staging arrays, or from the vendor headers.
# A human must never have to edit a table here after a driver update. Where
# a rule cannot be read it is derived, and where it cannot be derived the
# artefact says "unknown" rather than guessing.
#
# The three readers below all SELF-CHECK, for the reason drmtrace.sh's
# decoder does: a parser pointed at a file it does not understand produces a
# plausible, empty, wrong answer instead of an error.

# ---- provenance -------------------------------------------------------------
# Every generated artefact carries the same header. If two artefacts disagree
# about the driver they were measured on, that is visible in the file rather
# than in somebody's memory.

# lea_matrix_gpu_field FIELD -- one field out of `nvidia-smi -q`, or "unknown".
lea_matrix_gpu_field() {
    local v
    v=$(nvidia-smi -q 2>/dev/null | awk -F': ' -v f="$1" '
        $0 ~ "^ *" f " *:" { sub(/^[ \t]+/, "", $2); print $2; exit }')
    echo "${v:-unknown}"
}

# lea_matrix_driver -- the driver the measurement was taken against.
#
# The RUNNING driver, not DRIVER_VERSION: the artefacts describe what was
# measured. lea_matrix_check_driver is what refuses a mismatch.
lea_matrix_driver() {
    local v
    v=$(lea_driver_version) || v=""
    [[ -n $v ]] || v=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null | head -1)
    echo "${v:-unknown}"
}

# lea_matrix_check_driver -- the lockstep every binary in probe/ also does.
# A trace taken under a driver other than the one the tree targets resolves
# against the wrong headers, and every struct size in the catalogue is then
# a guess wearing a citation.
lea_matrix_check_driver() {
    local running want
    running=$(lea_matrix_driver)
    want=$(lea_want_driver)
    [[ $running == "$want" ]] && return 0
    error "driver lockstep: running $running, this tree targets $want.
The catalogue resolves signatures against vendor/ headers at $want, so a
trace taken under $running would be resolved against the wrong structs.
Fix: boot the pinned driver, or move DRIVER_VERSION and re-fetch
     (./scripts/build.sh vendor)."
    return 1
}

# lea_matrix_provenance [PREFIX] -- the header, one key per line, each line
# prefixed (e.g. "# " for markdown-adjacent files, "#" for TSV).
lea_matrix_provenance() {
    local p=${1-}
    local commit dirty=""
    commit=$(git -C "$LEA_ROOT" rev-parse --short HEAD 2>/dev/null) || commit=unknown
    git -C "$LEA_ROOT" diff --quiet 2>/dev/null || dirty=" (working tree modified)"
    printf '%sdriver:  %s\n' "$p" "$(lea_matrix_driver)"
    printf '%sgpu:     %s\n' "$p" "$(lea_matrix_gpu_field 'Product Name')"
    printf '%sarch:    %s (compute %s)\n' "$p" \
        "$(lea_matrix_gpu_field 'Product Architecture')" \
        "$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -1)"
    printf '%skernel:  %s\n' "$p" "$(uname -r)"
    printf '%sdate:    %s\n' "$p" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '%scommit:  %s%s\n' "$p" "$commit" "$dirty"
}

# ---- where things go --------------------------------------------------------
# One place, so no consumer computes a path of its own.
lea_matrix_dir()    { echo "$LEA_ROOT/matrix"; }
lea_matrix_traces() { echo "$LEA_ROOT/matrix/traces/$(lea_matrix_driver)"; }
lea_matrix_probes_dir() { echo "$LEA_ROOT/probe/matrix"; }

# ---- probe metadata ---------------------------------------------------------
# A probe declares itself in its own header. There is no registry file: the
# set of probes IS the set of scripts in probe/matrix/, and PROBES.md is
# generated by reading their headers. Adding a probe is adding one file.
#
#   # matrix-group:     compute | video | gl | vulkan | egl | compat | kms
#   # matrix-libs:      libcuda libnvidia-nvvm ...   (space separated, no .so)
#   # matrix-entry:     the entry API this probe exercises
#   # matrix-criterion: what is verified BEYOND the exit code
#   # matrix-status:    ready
#                     | declared-unsupported: <reason>
#                     | blocked: <reason>
#
# lea_matrix_meta FILE KEY -- the value, or empty.
#
# A value may wrap: a continuation is a following comment line that is
# INDENTED and does not open a key of its own. Without that, a criterion
# written on two lines lands in PROBES.md cut in half at the first line
# break -- which reads like a criterion that stops mid-sentence.
lea_matrix_meta() {
    awk -v k="# matrix-$2:" '
        index($0, k) == 1 { sub(/^[^:]*:[[:space:]]*/, ""); v = $0; on = 1; next }
        on {
            if ($0 !~ /^#[[:space:]][[:space:]]+/ || $0 ~ /^# matrix-/) { on = 0; next }
            line = $0; sub(/^#[[:space:]]+/, "", line); v = v " " line
        }
        END { if (v != "") print v }
    ' "$1"
}

# lea_matrix_probe_list -- every probe, in filename order.
lea_matrix_probe_list() {
    local d f
    d=$(lea_matrix_probes_dir)
    for f in "$d"/*.sh; do [[ -e $f ]] || continue; basename "$f" .sh; done
}

# ---- the counting rule ------------------------------------------------------
# What "how many ioctls did this workload make" means, in one place. It is
# the rule OPEN-QUESTIONS number 47 is about: both instruments were counted
# wrongly once, in opposite directions, and each wrong count looked like a
# finding about the other instrument. Anything that compares the two -- the
# native run, the guest run -- asks these five functions and never writes an
# awk line of its own.
#
# Three namespaces, never added together: the RM nodes, the NVKMS node, DRM.
# The strace patterns are disjoint by construction -- `/dev/nvidia-modeset`
# does not match the RM alternation, which is `ctl`, `-uvm` or a digit.

# lea_matrix_n_tracer TSV -- ioctls the tracer recorded on the RM nodes.
lea_matrix_n_tracer() {
    awk -F'\t' '$1=="ioctl" && $2!="drm" && $2!="render" && $2!="modeset"' "$1" | wc -l
}
# lea_matrix_n_tracer_kms TSV -- ... on /dev/nvidia-modeset.
lea_matrix_n_tracer_kms() { awk -F'\t' '$1=="ioctl" && $2=="modeset"' "$1" | wc -l; }
# lea_matrix_n_tracer_drm TSV -- ... on the DRM nodes. Counted, never gated.
lea_matrix_n_tracer_drm() {
    awk -F'\t' '$1=="ioctl" && ($2=="drm" || $2=="render")' "$1" | wc -l
}
# lea_matrix_n_strace STRACE -- the same count from strace -y.
#
# `_IOC(` and not the substring `_IOC`: strace prints a NAMED request for
# every ioctl it knows, and under an interpreter every isatty is a TCGETS2 --
# counting those made a tracer that missed nothing look 1062 calls short.
lea_matrix_n_strace() {
    grep '_IOC(' "$1" 2>/dev/null | grep -cE '/dev/nvidia(ctl|-uvm|[0-9])' || true
}
# lea_matrix_n_strace_kms STRACE -- ... on /dev/nvidia-modeset.
lea_matrix_n_strace_kms() {
    grep '_IOC(' "$1" 2>/dev/null | grep -c '/dev/nvidia-modeset' || true
}

# ---- the serial queue -------------------------------------------------------
# The GPU is a serial resource and these probes measure it. Two at once do not
# corrupt anything, they corrupt the MEASUREMENT -- a trace taken while
# another probe holds a channel is a different trace. The lock is held for
# the whole `trace` run, not per probe, so an operator who starts a second
# run waits instead of interleaving with the first.
#
# WARNING: `flock` on a file descriptor, never a pidfile check. A pidfile
# race has a window; flock does not.
#
# WARNING, and this one cost a run: the lock is held by a CHILD PROCESS and
# not by a descriptor of this shell. A descriptor this shell holds is
# INHERITED by everything it starts, and the guest phase starts three
# daemons that outlive it deliberately -- the two backends and
# cloud-hypervisor. Measured 2026-08-20: a guest run that had exited half an
# hour earlier still held this lock through its VM, and the next run sat in
# `flock` waiting for a lock whose owner was a virtual machine. Nothing in
# the trace phase could have shown it, because that phase starts no daemons.
#
# The holder takes the lock, says so through a file, and then waits for THIS
# shell to disappear. It watches with `kill -0` rather than through a pipe,
# because a pipe would be a descriptor again -- inherited by every daemon,
# which is the bug.
lea_matrix_serial() {
    local lock="$LEA_VM_DIR/ioctl-matrix.lock" ready i
    mkdir -p "$LEA_VM_DIR" || return 1
    ready=$(mktemp) || return 1
    (
        exec {f}>"$lock" || exit 1
        if ! flock -n "$f"; then
            echo waiting > "$ready"
            flock "$f" || exit 1
        fi
        echo held > "$ready"
        while kill -0 "$$" 2>/dev/null; do sleep 2; done
    ) &
    _LEA_MATRIX_LOCK_PID=$!
    lea_on_exit "kill $_LEA_MATRIX_LOCK_PID 2>/dev/null; rm -f $(printf '%q' "$ready"); true"
    for ((i = 0; i < 3600; i++)); do
        grep -q held "$ready" 2>/dev/null && return 0
        if [[ $i -eq 0 ]] && grep -q waiting "$ready" 2>/dev/null; then
            info "another ioctl-matrix run holds $lock -- waiting for it"
        fi
        kill -0 "$_LEA_MATRIX_LOCK_PID" 2>/dev/null || { error "the lock holder died"; return 1; }
        sleep 1
    done
    error "waited an hour for $lock"
    return 1
}

# ---- the probe contract -----------------------------------------------------
# A probe runs its ONE workload through lea_matrix_workload. The runner puts
# the tracer (or strace) around exactly that call and around nothing else.
#
# WHY THE WRAPPER IS HERE AND NOT AROUND THE SCRIPT: the tracer opens
# LEA_TRACE_FILE with O_TRUNC in its constructor. Preloaded into the probe
# script itself, every `mkdir`, every `awk` and every forked child of the
# workload would truncate the trace of the run in progress -- and the loss
# is silent, because a truncated file is still a valid file. So the shell
# stays outside the wrapper and only the workload goes in.
#
# Run without the runner (probe/matrix/<name>.sh on its own) the wrapper is
# empty and the probe is just a PASS/FAIL check of the feature path.
lea_matrix_workload() {
    if [[ -n ${LEA_MATRIX_WRAP:-} ]]; then
        # Deliberately word-split: LEA_MATRIX_WRAP is a command prefix.
        # shellcheck disable=SC2086
        $LEA_MATRIX_WRAP "$@"
    else
        "$@"
    fi
}

# lea_matrix_criterion TEXT -- what this run actually verified. The runner
# reads this line back out of the probe's stdout; a probe that exits 0
# without printing it has not stated what it proved and does not pass.
lea_matrix_criterion() { echo "CRITERION: $*"; }

# lea_matrix_unsupported -- a probe that cannot run here says so from its own
# header, so the reason exists in exactly one place. Exit 2, never 1: a
# declared reason is not a failure.
lea_matrix_unsupported() {
    local reason
    reason=$(lea_matrix_meta "$0" status)
    echo "${reason:-declared-unsupported: no reason recorded in the header}"
    exit 2
}

# ---- library inventories ----------------------------------------------------
# Two inventories and their difference. What is ABSENT from the guest is the
# most important line in a feature guarantee, so it has to be data.

# lea_matrix_libdir / lea_matrix_libdir32 -- the same discovery the staging
# uses, so the inventory describes the directory the guest is actually fed
# from and not a directory that merely exists.
lea_matrix_libdir()   { lea_nvidia_libdir "$(lea_want_driver)"; }
lea_matrix_libdir32() { echo "${LEA_NVIDIA_LIB32_DIR:-/usr/lib32}"; }

# lea_matrix_stage_array FILE NAME -- one `local -a NAME=(...)` array out of
# a shell source file, comments stripped, one entry per line.
#
# This is how the guest-staged set is READ rather than transcribed: the
# arrays in scripts/lib/provision.sh are the definition of what the guest
# gets, and a second copy of them here would be exactly the hand-maintained
# table this whole pipeline refuses to have. Referring to them BY NAME is a
# code reference; copying their contents would be a table.
lea_matrix_stage_array() {
    awk -v n="$2" '
        index($0, "local -a " n "=(") { on = 1; sub(/^.*=\(/, "") }
        on {
            line = $0
            sub(/[[:space:]]*#.*$/, "", line)       # a trailing or whole-line comment
            fin = (index(line, ")") > 0)
            sub(/\).*$/, "", line)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)
            if (line != "") print line
            if (fin) exit
        }
    ' "$1" | tr ' ' '\n' | sed '/^$/d'
}

# The six arrays that define the payload, named where they are defined.
# lea_payload_stage: the compute set. lea_gl_stage: GL/EGL/Vulkan and the
# 32-bit half.
_LEA_MATRIX_ARRAYS_64="libs optional versioned loose"
_LEA_MATRIX_ARRAYS_32="versioned32 optional32"

# lea_matrix_staged BITS -- the staged set, one bare library name per line
# (no .so suffix, no version). BITS is 64 or 32.
lea_matrix_staged() {
    local a names
    [[ $1 == 32 ]] && names=$_LEA_MATRIX_ARRAYS_32 || names=$_LEA_MATRIX_ARRAYS_64
    for a in $names; do
        lea_matrix_stage_array "$LEA_ROOT/scripts/lib/provision.sh" "$a"
    done | sed 's/\.so.*$//' | sort -u
}

# lea_matrix_staged_check -- the self-check. An awk parser aimed at a file
# whose shape has moved returns nothing and looks like "the guest stages
# nothing", which would turn every library into a not-staged row and read
# like a catastrophic finding. Empty is therefore an error, loudly.
lea_matrix_staged_check() {
    local a n bad=0
    for a in $_LEA_MATRIX_ARRAYS_64 $_LEA_MATRIX_ARRAYS_32; do
        n=$(lea_matrix_stage_array "$LEA_ROOT/scripts/lib/provision.sh" "$a" | wc -l)
        [[ $n -gt 0 ]] || { error "staging array '$a' read as empty from scripts/lib/provision.sh"; bad=1; }
    done
    [[ $bad -eq 0 ]] || {
        error "the staged-set reader no longer understands provision.sh.
Every library would be reported as not-staged, which is a wrong answer that
looks like a finding. Fix the reader (lea_matrix_stage_array) before
trusting any artefact from this run."
        return 1
    }
    return 0
}

# lea_matrix_driver_packages -- every installed package AT the driver
# version, one name per line.
#
# NOT a list of package names. NVIDIA's userspace is split differently by
# every distribution -- on this host `libnvidia-opencl` is in `opencl-nvidia`
# and not in `nvidia-utils`, and asking `nvidia-utils` alone reported OpenCL
# as a library the driver does not ship at all, while a probe was computing
# with it. The version IS the driver package: anything installed at exactly
# DRIVER_VERSION came out of the same release.
lea_matrix_driver_packages() {
    command -v pacman >/dev/null 2>&1 || return 1
    pacman -Q 2>/dev/null | awk -v v="$(lea_want_driver)" '$2 ~ "^" v "-" { print $1 }'
}

# lea_matrix_host_payload BITS -- every library the INSTALLED host driver
# ships, one bare name per line.
#
# Primary source is the package manager's manifest, because that is what the
# word "ships" means. Where there is none, the fallback is the version
# suffix: a file called <name>.so.<DRIVER_VERSION> in the driver's library
# directory came out of the driver package by construction. Which of the two
# answered is recorded in DISCOVERY.md -- the inventories are only as good as
# their source and the artefact has to say which one it was.
lea_matrix_host_payload() {
    local bits=${1:-64} want dir pkg
    want=$(lea_want_driver)
    if [[ $bits == 32 ]]; then dir=$(lea_matrix_libdir32)
    else dir=$(lea_matrix_libdir) || return 1
    fi
    if [[ -n $(lea_matrix_driver_packages) ]]; then
        for pkg in $(lea_matrix_driver_packages); do
            pacman -Ql "$pkg" 2>/dev/null | awk -v d="$dir/" '{ if (index($2, d) == 1) print $2 }'
        done | xargs -r -n1 basename \
            | grep -E '\.so\.[0-9]' | sed 's/\.so\..*$//' | sort -u
        return 0
    fi
    if command -v dpkg-query >/dev/null 2>&1 \
       && dpkg-query -L "libnvidia-compute-${want%%.*}" >/dev/null 2>&1; then
        dpkg-query -L "libnvidia-compute-${want%%.*}" 2>/dev/null \
            | grep -E '\.so\.[0-9]' | xargs -r -n1 basename \
            | sed 's/\.so\..*$//' | sort -u
        return 0
    fi
    ls -1 "$dir" 2>/dev/null | grep -F ".so.$want" | sed 's/\.so\..*$//' | sort -u
}

# lea_matrix_host_payload_source BITS -- which of the three answered.
lea_matrix_host_payload_source() {
    local pkgs
    pkgs=$(lea_matrix_driver_packages | tr '\n' ' ')
    if [[ -n ${pkgs// /} ]]; then
        echo "pacman -Ql over every package at $(lea_want_driver): ${pkgs% }"
    elif command -v dpkg-query >/dev/null 2>&1; then
        echo "dpkg-query -L (Debian/Ubuntu driver package)"
    else
        echo "filesystem: *.so.$(lea_want_driver) in the driver library directory"
    fi
}

# lea_matrix_not_staged -- host payload minus staged set, per bit width.
# Prints "<name> <where-it-is-staged-instead>" so that "not staged at all"
# and "staged only for the other bit width" stay different findings.
lea_matrix_not_staged() {
    local s64 s32 h64 n
    s64=$(lea_matrix_staged 64); s32=$(lea_matrix_staged 32)
    h64=$(lea_matrix_host_payload 64)
    while read -r n; do
        [[ -n $n ]] || continue
        grep -qxF "$n" <<<"$s64" && continue
        if grep -qxF "$n" <<<"$s32"; then
            echo "$n	staged 32-bit only"
        else
            echo "$n	not staged at all"
        fi
    done <<<"$h64"
}
