/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * nvrm_wire.h -- GENERATED, DO NOT EDIT BY HAND.
 *
 * Source: crates/nvrm-wire (Req/Rsp/table format), generated by
 *   cargo run --release --bin nvrm-genhdr -- guest-module/virtio_nvrm/nvrm_wire.h
 *
 * Every offset carries a _Static_assert: the C side cannot even be
 * built against a wrong layout. Whoever changes the wire structs in
 * Rust regenerates this header and checks it in with the change.
 */

#ifndef _NVRM_WIRE_H_
#define _NVRM_WIRE_H_

#include <linux/types.h>
#include <linux/stddef.h>

/* ---- protocol ---- */
#define NVRM_PROTO_VERSION	6u
#define NVRM_DRIVER_VERSION	"610.43.03"
#define NVRM_NONE_U32		4294967295u
#define NVRM_NONE_U64		18446744073709551615ull
#define NVRM_MAX_PAYLOAD	16384u
#define NVRM_MAX_AUX		1048576u
#define NVRM_MAX_MSG		1069056u
#define NVRM_MAX_NESTED		4u

/* Kind: what sort of request this is. */
#define NVRM_KIND_HELLO	0u
#define NVRM_KIND_OPEN	1u
#define NVRM_KIND_CLOSE	2u
#define NVRM_KIND_IOCTL	3u
#define NVRM_KIND_MAP_PREPARE	4u
#define NVRM_KIND_UVM_POOL_BACK	5u
#define NVRM_KIND_GET_TABLES	6u
#define NVRM_KIND_MAP_RELEASE	7u
#define NVRM_KIND_PROC_GONE	8u
#define NVRM_KIND_EVENT_FIRED	9u

/* DevTag: which device node. */
#define NVRM_DEV_CTL	0u
#define NVRM_DEV_GPU	1u
#define NVRM_DEV_UVM	2u
#define NVRM_DEV_UVM_TOOLS	3u

/* ---- kernel RM API (NVKMS): op -> escape + params size ---- */
#define NVRM_KOP_FREE		0u
#define NVRM_KESC_FREE	41u
#define NVRM_KSIZE_FREE	16u
#define NVRM_KOP_ALLOC		21u
#define NVRM_KESC_ALLOC	43u
#define NVRM_KSIZE_ALLOC	48u
#define NVRM_KOP_CONTROL		54u
#define NVRM_KESC_CONTROL	42u
#define NVRM_KSIZE_CONTROL	32u
#define NVRM_KOP_DUP_OBJECT		55u
#define NVRM_KESC_DUP_OBJECT	52u
#define NVRM_KSIZE_DUP_OBJECT	28u
#define NVRM_KOP_MAP_MEMORY		33u
#define NVRM_KESC_MAP_MEMORY	78u
#define NVRM_KSIZE_MAP_MEMORY	48u
#define NVRM_KOP_UNMAP_MEMORY		34u
#define NVRM_KESC_UNMAP_MEMORY	79u
#define NVRM_KSIZE_UNMAP_MEMORY	32u
#define NVRM_KOP_MAP_MEMORY_DMA		46u
#define NVRM_KESC_MAP_MEMORY_DMA	87u
#define NVRM_KSIZE_MAP_MEMORY_DMA	64u
#define NVRM_KOP_UNMAP_MEMORY_DMA		47u
#define NVRM_KESC_UNMAP_MEMORY_DMA	88u
#define NVRM_KSIZE_UNMAP_MEMORY_DMA	48u
/* ---- the virtual display (NVA083_GRID_DISPLAYLESS) ---- */
#define NVRM_CLASS_DISPLAY_COMMON	0x73u
#define NVRM_CLASS_DISPLAYLESS	0xa083u
#define NVRM_CTRL_GET_CLASSLIST	0x800201u
#define NVRM_CTRL_VD_GET_NUM_HEADS	0xa0830101u
#define NVRM_CTRL_VD_GET_MAX_RES	0xa0830102u
#define NVRM_CTRL_VD_GET_EDID	0xa0830103u
#define NVRM_CTRL_VD_IS_ACTIVE	0xa0830104u
#define NVRM_CTRL_VD_IS_CONNECTED	0xa0830105u
#define NVRM_CTRL_VD_GET_MAX_PIXELS	0xa0830106u
#define NVRM_CTRL_GC6_BLOCKER	0x20803d01u
#define NVRM_CTRL_VT_SWITCH	0x801e01u
#define NVRM_CTRL_VT_GET_FB_INFO	0x801e02u
#define NVRM_CLASS_VBLANK_CALLBACK	0x9010u
#define NVRM_CTRL_SET_VBLANK_NOTIFY	0x90100101u
#define NVRM_CLASS_EVENT_OS_EVENT	0x79u
#define NVRM_CLASS_EVENT_KERNEL_CALLBACK	0x78u
#define NVRM_CLASS_EVENT_KERNEL_CALLBACK_EX	0x7eu
#define NVRM_ESC_RM_GET_EVENT_DATA	0x52u
#define NVRM_NOTIFIER_DP_IRQ	0x7u
#define NVRM_NOTIFIER_HDMI_FRL_RETRAIN	0xb2u
#define NVRM_NOTIFIER_LPWR_DIFR_PREFETCH	0xa2u
#define NVRM_NOTIFY_INDEX_MASK	0xffffu
#define NVRM_NV_ERR_OBJECT_NOT_FOUND	0x57u
#define NVRM_NV_ERR_BUFFER_TOO_SMALL	0x2u
#define NVRM_NV_ERR_INVALID_ARGUMENT	0x1fu
#define NVRM_DISP_CLASS_COUNT	14u
#define NVRM_DISP_CLASSES	{ 0xcc70u, 0xcb70u, 0xca70u, 0xc970u, 0xc870u, 0xc770u, 0xc670u, 0xc570u, 0xc57au, 0xc67au, 0xc97au, 0xca7au, 0xcb7au, 0xcc7au, }

#define NVRM_KESC_REGISTER_FD	201u
#define NVRM_KSIZE_REGISTER_FD	4u

/* ---- NVOS64 (alloc) and NVOS54 (control), for the fields we write ---- */
#define NVRM_NVOS64_HROOT_OFF	0u
#define NVRM_NVOS64_HOBJECTPARENT_OFF	4u
#define NVRM_NVOS64_HOBJECTNEW_OFF	8u
#define NVRM_NVOS64_HCLASS_OFF	12u
#define NVRM_NVOS64_PALLOCPARMS_OFF	16u
#define NVRM_NVOS64_STATUS_OFF	40u
#define NVRM_NVOS54_HCLIENT_OFF	0u
#define NVRM_NVOS54_HOBJECT_OFF	4u
#define NVRM_NVOS54_CMD_OFF	8u
#define NVRM_NVOS54_PARAMS_OFF	16u
#define NVRM_NVOS54_PARAMSSIZE_OFF	24u
#define NVRM_NVOS54_STATUS_OFF	28u

/* ---- the event return channel: NV0005 / NVOS41 / NVOS10_EX ---- */
#define NVRM_NVOS41_PEVENT_OFF	0u
#define NVRM_NVOS41_MOREEVENTS_OFF	8u
#define NVRM_NVOS41_STATUS_OFF	12u
#define NVRM_NV0005_HPARENTCLIENT_OFF	0u
#define NVRM_NV0005_HCLASS_OFF	8u
#define NVRM_NV0005_NOTIFYINDEX_OFF	12u
#define NVRM_NV0005_DATA_OFF	16u
#define NVRM_NVOS10_CB_EX_FUNC_OFF	0u
#define NVRM_NVOS10_CB_EX_ARG_OFF	8u
#define NVRM_NVOS41_SIZE	16u
#define NVRM_NVOS10_CB_EX_SIZE	16u
#define NVRM_NVUNIXEVENT_SIZE	16u

/* ---- semaphore-surface waiters (NV_SEMAPHORE_SURFACE, class 0x00da) ----
 * ctrl00da.h: the handle is an OS-event id (NvU32) for user clients and a
 * kernel pointer to an NVOS10_EVENT_KERNEL_CALLBACK_EX for kernel clients
 * (sem_surf.c:1699-1710) -- which is how the two are told apart. */
#define NVRM_CTRL_SEMSURF_REG_WAITER	0xda0003u
#define NVRM_CTRL_SEMSURF_UNREG_WAITER	0xda0005u
#define NVRM_SEMSURF_REG_HANDLE_OFF	24u
#define NVRM_SEMSURF_UNREG_HANDLE_OFF	16u

/* ---- root-client controls behind enumerate_gpus ---- */
#define NVRM_CTRL_GPU_GET_PROBED_IDS	0x214u
#define NVRM_CTRL_GPU_GET_PCI_INFO	0x21bu
#define NVRM_SIZE_PROBED_IDS	384u
#define NVRM_SIZE_PCI_INFO	12u
#define NVRM_PCI_INFO_GPUID_OFF	0u
#define NVRM_PCI_INFO_DOMAIN_OFF	4u
#define NVRM_PCI_INFO_BUS_OFF	8u
#define NVRM_PCI_INFO_SLOT_OFF	10u
#define NVRM_MAX_DEVICES	32u
#define NVRM_GPU_INVALID_ID	0xffffffffu

/* ---- controls carrying a gpuId or a PCI address ---- */
#define NVRM_CTRL_GPU_GET_ATTACHED_IDS	0x201u
#define NVRM_CTRL_GPU_GET_ID_INFO	0x202u
#define NVRM_SIZE_ATTACHED_IDS	128u
#define NVRM_SIZE_ID_INFO	40u
#define NVRM_ID_INFO_GPUID_OFF	0u
#define NVRM_MAX_ATTACHED_GPUS	32u

#define NVRM_KWIRE_MAP_MEMORY	56u
/* ---- NVOS33 (map) and NVOS34 (unmap), fields we touch ---- */
#define NVRM_NVOS33_LENGTH_OFF	24u
#define NVRM_NVOS33_LINEAR_OFF	32u
#define NVRM_NVOS33_FLAGS_OFF	44u
#define NVRM_NVOS33_STATUS_OFF	40u
#define NVRM_NVOS34_LINEAR_OFF	16u
#define NVRM_NVOS34_STATUS_OFF	24u
#define NVRM_NVOS33_FLAGS_MEM_SPACE_USER	0x4000u

/* ---- OS descriptor kinds (nvos.h) ---- */
#define NVRM_OSDESC_TYPE_OFF	32u
#define NVRM_OSDESC_DESCRIPTOR_OFF	16u
#define NVRM_OSDESC_LIMIT_OFF	24u
#define NVRM_OSDESC_PARAMS_SIZE	40u
#define NVRM_OSDESC_SGT_OFF	0u
#define NVRM_OSDESC_VIRTUAL_ADDRESS	0u
#define NVRM_OSDESC_OS_PAGE_ARRAY	1u
#define NVRM_OSDESC_OS_IO_MEMORY	2u
#define NVRM_OSDESC_OS_PHYS_ADDR	3u
#define NVRM_OSDESC_OS_FILE_HANDLE	4u
#define NVRM_OSDESC_OS_DMA_BUF_PTR	5u
#define NVRM_OSDESC_OS_SGT_PTR	6u

/* ---- every control whose params carry a gpuId ---- */
/* { cmd, offset } -- one gpuId at a fixed offset */
#define NVRM_BDF_SCALARS \
	{ 0x202u, 0u }, /* GET_ID_INFO */ \
	{ 0x205u, 0u }, /* GET_ID_INFO_V2 */ \
	{ 0x202u, 28u }, /* GET_ID_INFO boardId */ \
	{ 0x205u, 20u }, /* GET_ID_INFO_V2 boardId */ \
	{ 0x21bu, 0u }, /* GET_PCI_INFO */ \
	{ 0x274u, 260u }, /* GET_UUID_INFO */ \
	{ 0x275u, 0u }, /* GET_UUID_FROM_GPU_ID */ \
	{ 0x278u, 0u }, /* MODIFY_DRAIN_STATE */ \
	{ 0x279u, 0u }, /* QUERY_DRAIN_STATE */ \
	{ 0x289u, 0u }, /* ASYNC_ATTACH_ID */ \
	{ 0x290u, 0u }  /* WAIT_ATTACH_ID */
#define NVRM_CTRL_BUS_GET_INFO	0x20801802u
#define NVRM_CTRL_BUS_GET_INFO_V2	0x20801823u
#define NVRM_BUS_INFO_LIST_OFF	4u
#define NVRM_BUS_INFO_ENTRY_SIZE	8u
#define NVRM_BUS_INFO_DATA_OFF	4u
#define NVRM_BUS_INFO_MAX_LIST	52u
#define NVRM_BUS_INFO_INDEX_BUS	0xfu
#define NVRM_BUS_INFO_INDEX_DEVICE	0x10u
#define NVRM_BUS_INFO_INDEX_DOMAIN	0x2cu
#define NVRM_ESC_CARD_INFO	200u
#define NVRM_ESC_ATTACH_GPUS_TO_FD	212u
#define NVRM_CARD_INFO_ENTRY	72u
#define NVRM_CARD_INFO_VALID_OFF	0u
#define NVRM_CARD_INFO_GPUID_OFF	16u
#define NVRM_CARD_INFO_PCI_OFF	4u
#define NVRM_PCI_DOMAIN_OFF	0u
#define NVRM_PCI_BUS_OFF	4u
#define NVRM_PCI_SLOT_OFF	5u
#define NVRM_PCI_FUNC_OFF	6u
/* { cmd, offset, count, stride } -- an array of gpuIds, `stride` bytes apart */
#define NVRM_BDF_ARRAYS \
	{ 0x201u, 0u, 32u, 4u }, /* GET_ATTACHED_IDS */ \
	{ 0x214u, 0u, 32u, 4u }, /* GET_PROBED_IDS */ \
	{ 0x215u, 0u, 32u, 4u }, /* ATTACH_IDS */ \
	{ 0x216u, 0u, 32u, 4u }, /* DETACH_IDS */ \
	{ 0x288u, 4u, 256u, 12u }, /* GET_ACTIVE_DEVICE_IDS */ \
	{ 0x13au, 8u, 8u, 4u }, /* P2P_CAPS_MATRIX_A */ \
	{ 0x13au, 40u, 8u, 4u }  /* P2P_CAPS_MATRIX_B */

/* ---- offset of `status` per op, so a refusal can be stated ---- */
#define NVRM_KSTAT_FREE	0u, 12u
#define NVRM_KSTAT_ALLOC_MEMORY	2u, 40u
#define NVRM_KSTAT_ALLOC	21u, 40u
#define NVRM_KSTAT_MAP_MEMORY	33u, 40u
#define NVRM_KSTAT_UNMAP_MEMORY	34u, 24u
#define NVRM_KSTAT_ALLOC_CONTEXT_DMA	39u, 48u
#define NVRM_KSTAT_MAP_MEMORY_DMA	46u, 56u
#define NVRM_KSTAT_UNMAP_MEMORY_DMA	47u, 40u
#define NVRM_KSTAT_BIND_CONTEXT_DMA	49u, 12u
#define NVRM_KSTAT_CONTROL	54u, 28u
#define NVRM_KSTAT_DUP_OBJECT	55u, 24u
#define NVRM_KSTAT_SHARE	62u, 20u
#define NVRM_KSTAT_ADD_VBLANK_CALLBACK	61u, 52u
#define NVRM_KOP_VID_HEAP_CONTROL	32u
#define NVRM_NV_ERR_NOT_SUPPORTED	0x56u

/* ---- the wire: request and reply ---- */

struct nvrm_nested_desc {
	__u32 ptr_off;
	__u32 aux_off;
	__u32 len;
	__u32 pad;
};
_Static_assert(sizeof(struct nvrm_nested_desc) == 16, "nvrm_nested_desc: size");
_Static_assert(_Alignof(struct nvrm_nested_desc) == 4, "nvrm_nested_desc: alignment");
_Static_assert(offsetof(struct nvrm_nested_desc, ptr_off) == 0, "nvrm_nested_desc.ptr_off");
_Static_assert(offsetof(struct nvrm_nested_desc, aux_off) == 4, "nvrm_nested_desc.aux_off");
_Static_assert(offsetof(struct nvrm_nested_desc, len) == 8, "nvrm_nested_desc.len");
_Static_assert(offsetof(struct nvrm_nested_desc, pad) == 12, "nvrm_nested_desc.pad");

struct nvrm_req {
	__u32 seq;
	__u32 kind;
	__u32 dev_tag;
	__u32 ioctl_nr;
	__u64 target_token;
	__u32 inline_len;
	__u32 aux_len;
	__u32 fd_field_off;
	__u32 fd_field_proc;
	__u64 fd_field_token;
	__u32 embedded_ptr_off;
	__u32 nested_count;
	struct nvrm_nested_desc nested[NVRM_MAX_NESTED];
	__u32 aux_fd_field_off;
	__u32 aux_fd_field_proc;
	__u64 aux_fd_field_token;
	__u64 map_len;
	__u64 addr;
	__u32 gpa_run_count;
	__u32 guest_proc;
};
_Static_assert(sizeof(struct nvrm_req) == 160, "nvrm_req: size");
_Static_assert(_Alignof(struct nvrm_req) == 8, "nvrm_req: alignment");
_Static_assert(offsetof(struct nvrm_req, seq) == 0, "nvrm_req.seq");
_Static_assert(offsetof(struct nvrm_req, kind) == 4, "nvrm_req.kind");
_Static_assert(offsetof(struct nvrm_req, dev_tag) == 8, "nvrm_req.dev_tag");
_Static_assert(offsetof(struct nvrm_req, ioctl_nr) == 12, "nvrm_req.ioctl_nr");
_Static_assert(offsetof(struct nvrm_req, target_token) == 16, "nvrm_req.target_token");
_Static_assert(offsetof(struct nvrm_req, inline_len) == 24, "nvrm_req.inline_len");
_Static_assert(offsetof(struct nvrm_req, aux_len) == 28, "nvrm_req.aux_len");
_Static_assert(offsetof(struct nvrm_req, fd_field_off) == 32, "nvrm_req.fd_field_off");
_Static_assert(offsetof(struct nvrm_req, fd_field_proc) == 36, "nvrm_req.fd_field_proc");
_Static_assert(offsetof(struct nvrm_req, fd_field_token) == 40, "nvrm_req.fd_field_token");
_Static_assert(offsetof(struct nvrm_req, embedded_ptr_off) == 48, "nvrm_req.embedded_ptr_off");
_Static_assert(offsetof(struct nvrm_req, nested_count) == 52, "nvrm_req.nested_count");
_Static_assert(offsetof(struct nvrm_req, nested) == 56, "nvrm_req.nested");
_Static_assert(offsetof(struct nvrm_req, aux_fd_field_off) == 120, "nvrm_req.aux_fd_field_off");
_Static_assert(offsetof(struct nvrm_req, aux_fd_field_proc) == 124, "nvrm_req.aux_fd_field_proc");
_Static_assert(offsetof(struct nvrm_req, aux_fd_field_token) == 128, "nvrm_req.aux_fd_field_token");
_Static_assert(offsetof(struct nvrm_req, map_len) == 136, "nvrm_req.map_len");
_Static_assert(offsetof(struct nvrm_req, addr) == 144, "nvrm_req.addr");
_Static_assert(offsetof(struct nvrm_req, gpa_run_count) == 152, "nvrm_req.gpa_run_count");
_Static_assert(offsetof(struct nvrm_req, guest_proc) == 156, "nvrm_req.guest_proc");

struct nvrm_rsp {
	__u32 seq;
	__s32 ret;
	__u64 token;
	__u32 inline_len;
	__u32 aux_len;
	__u32 scm_fd_count;
	__u32 pad;
};
_Static_assert(sizeof(struct nvrm_rsp) == 32, "nvrm_rsp: size");
_Static_assert(_Alignof(struct nvrm_rsp) == 8, "nvrm_rsp: alignment");
_Static_assert(offsetof(struct nvrm_rsp, seq) == 0, "nvrm_rsp.seq");
_Static_assert(offsetof(struct nvrm_rsp, ret) == 4, "nvrm_rsp.ret");
_Static_assert(offsetof(struct nvrm_rsp, token) == 8, "nvrm_rsp.token");
_Static_assert(offsetof(struct nvrm_rsp, inline_len) == 16, "nvrm_rsp.inline_len");
_Static_assert(offsetof(struct nvrm_rsp, aux_len) == 20, "nvrm_rsp.aux_len");
_Static_assert(offsetof(struct nvrm_rsp, scm_fd_count) == 24, "nvrm_rsp.scm_fd_count");
_Static_assert(offsetof(struct nvrm_rsp, pad) == 28, "nvrm_rsp.pad");

struct nvrm_proc_info {
	__u32 pid;
	__u32 pad;
	char comm[16];
};
_Static_assert(sizeof(struct nvrm_proc_info) == 24, "nvrm_proc_info: size");
_Static_assert(_Alignof(struct nvrm_proc_info) == 4, "nvrm_proc_info: alignment");
_Static_assert(offsetof(struct nvrm_proc_info, pid) == 0, "nvrm_proc_info.pid");
_Static_assert(offsetof(struct nvrm_proc_info, pad) == 4, "nvrm_proc_info.pad");
_Static_assert(offsetof(struct nvrm_proc_info, comm) == 8, "nvrm_proc_info.comm");

/* One GPA run, as UvmPoolBack and the OS descriptor send it along.
 * Layout identical to host_pool::GpaRun (16 bytes on the wire) and
 * struct nvrm_nodes_gpa_run. */
struct nvrm_gpa_run {
	__u64 gpa;
	__u64 len;
};
_Static_assert(sizeof(struct nvrm_gpa_run) == 16, "nvrm_gpa_run: size");

/* ---- descriptor tables (the host sends them, we interpret) ---- */

#define NVRM_TABLE_MAGIC	0x5452564eu
#define NVRM_TABLE_VERSION	1u
#define NVRM_SIZE_FROM_IOC	4294967295u

#define NVRM_EMB_NONE	0u
#define NVRM_EMB_LEN_FIELD	1u
#define NVRM_EMB_LEN_CLASS	2u
#define NVRM_EMB_LEN_FIXED	3u
#define NVRM_NLEN_FIXED	0u
#define NVRM_NLEN_FIELD	1u
#define NVRM_F_XFER	1u
#define NVRM_F_OSDESC	2u
#define NVRM_F_FREE	4u
#define NVRM_CF_BLOCK	1u
#define NVRM_CF_FD	2u
#define NVRM_KF_UNVERIFIED	1u

struct nvrm_table_hdr {
	__u32 magic;
	__u32 table_version;
	__u32 total_len;
	__u32 checksum;
	__u32 n_ioctl;
	__u32 n_class;
	__u32 n_ctrl;
	__u32 n_nested;
	__u32 xfer_nr;
	__u32 xfer_struct_len;
	__u32 xfer_cmd_off;
	__u32 xfer_size_off;
	__u32 xfer_ptr_off;
	__u32 max_ioctl_size;
	__u32 osdesc_class;
	__u32 osdesc_pmem_off;
	__u32 osdesc_limit_off;
	__u32 osdesc_status_off;
	__u32 osdesc_handle_off;
	__u32 max_inline;
	__u32 max_aux;
	__u32 max_nested;
	__u32 pad[2];
};
_Static_assert(sizeof(struct nvrm_table_hdr) == 96, "nvrm_table_hdr: size");
_Static_assert(_Alignof(struct nvrm_table_hdr) == 4, "nvrm_table_hdr: alignment");
_Static_assert(offsetof(struct nvrm_table_hdr, magic) == 0, "nvrm_table_hdr.magic");
_Static_assert(offsetof(struct nvrm_table_hdr, table_version) == 4, "nvrm_table_hdr.table_version");
_Static_assert(offsetof(struct nvrm_table_hdr, total_len) == 8, "nvrm_table_hdr.total_len");
_Static_assert(offsetof(struct nvrm_table_hdr, checksum) == 12, "nvrm_table_hdr.checksum");
_Static_assert(offsetof(struct nvrm_table_hdr, n_ioctl) == 16, "nvrm_table_hdr.n_ioctl");
_Static_assert(offsetof(struct nvrm_table_hdr, n_class) == 20, "nvrm_table_hdr.n_class");
_Static_assert(offsetof(struct nvrm_table_hdr, n_ctrl) == 24, "nvrm_table_hdr.n_ctrl");
_Static_assert(offsetof(struct nvrm_table_hdr, n_nested) == 28, "nvrm_table_hdr.n_nested");
_Static_assert(offsetof(struct nvrm_table_hdr, xfer_nr) == 32, "nvrm_table_hdr.xfer_nr");
_Static_assert(offsetof(struct nvrm_table_hdr, xfer_struct_len) == 36, "nvrm_table_hdr.xfer_struct_len");
_Static_assert(offsetof(struct nvrm_table_hdr, xfer_cmd_off) == 40, "nvrm_table_hdr.xfer_cmd_off");
_Static_assert(offsetof(struct nvrm_table_hdr, xfer_size_off) == 44, "nvrm_table_hdr.xfer_size_off");
_Static_assert(offsetof(struct nvrm_table_hdr, xfer_ptr_off) == 48, "nvrm_table_hdr.xfer_ptr_off");
_Static_assert(offsetof(struct nvrm_table_hdr, max_ioctl_size) == 52, "nvrm_table_hdr.max_ioctl_size");
_Static_assert(offsetof(struct nvrm_table_hdr, osdesc_class) == 56, "nvrm_table_hdr.osdesc_class");
_Static_assert(offsetof(struct nvrm_table_hdr, osdesc_pmem_off) == 60, "nvrm_table_hdr.osdesc_pmem_off");
_Static_assert(offsetof(struct nvrm_table_hdr, osdesc_limit_off) == 64, "nvrm_table_hdr.osdesc_limit_off");
_Static_assert(offsetof(struct nvrm_table_hdr, osdesc_status_off) == 68, "nvrm_table_hdr.osdesc_status_off");
_Static_assert(offsetof(struct nvrm_table_hdr, osdesc_handle_off) == 72, "nvrm_table_hdr.osdesc_handle_off");
_Static_assert(offsetof(struct nvrm_table_hdr, max_inline) == 76, "nvrm_table_hdr.max_inline");
_Static_assert(offsetof(struct nvrm_table_hdr, max_aux) == 80, "nvrm_table_hdr.max_aux");
_Static_assert(offsetof(struct nvrm_table_hdr, max_nested) == 84, "nvrm_table_hdr.max_nested");
_Static_assert(offsetof(struct nvrm_table_hdr, pad) == 88, "nvrm_table_hdr.pad");

struct nvrm_ioctl_desc {
	__u32 dev;
	__u32 nr;
	__u32 size;
	__u32 fd_off;
	__u32 emb_ptr_off;
	__u32 emb_len_kind;
	__u32 emb_len_off;
	__u32 cmd_off;
	__u32 rights_off;
	__u32 rights_if_size;
	__u32 handle_off;
	__u32 flags;
};
_Static_assert(sizeof(struct nvrm_ioctl_desc) == 48, "nvrm_ioctl_desc: size");
_Static_assert(_Alignof(struct nvrm_ioctl_desc) == 4, "nvrm_ioctl_desc: alignment");
_Static_assert(offsetof(struct nvrm_ioctl_desc, dev) == 0, "nvrm_ioctl_desc.dev");
_Static_assert(offsetof(struct nvrm_ioctl_desc, nr) == 4, "nvrm_ioctl_desc.nr");
_Static_assert(offsetof(struct nvrm_ioctl_desc, size) == 8, "nvrm_ioctl_desc.size");
_Static_assert(offsetof(struct nvrm_ioctl_desc, fd_off) == 12, "nvrm_ioctl_desc.fd_off");
_Static_assert(offsetof(struct nvrm_ioctl_desc, emb_ptr_off) == 16, "nvrm_ioctl_desc.emb_ptr_off");
_Static_assert(offsetof(struct nvrm_ioctl_desc, emb_len_kind) == 20, "nvrm_ioctl_desc.emb_len_kind");
_Static_assert(offsetof(struct nvrm_ioctl_desc, emb_len_off) == 24, "nvrm_ioctl_desc.emb_len_off");
_Static_assert(offsetof(struct nvrm_ioctl_desc, cmd_off) == 28, "nvrm_ioctl_desc.cmd_off");
_Static_assert(offsetof(struct nvrm_ioctl_desc, rights_off) == 32, "nvrm_ioctl_desc.rights_off");
_Static_assert(offsetof(struct nvrm_ioctl_desc, rights_if_size) == 36, "nvrm_ioctl_desc.rights_if_size");
_Static_assert(offsetof(struct nvrm_ioctl_desc, handle_off) == 40, "nvrm_ioctl_desc.handle_off");
_Static_assert(offsetof(struct nvrm_ioctl_desc, flags) == 44, "nvrm_ioctl_desc.flags");

struct nvrm_class_desc {
	__u32 hclass;
	__u32 param_size;
	__u32 fd_off;
	__u32 flags;
	__u32 fd_if_off;
	__u32 fd_if_val;
};
_Static_assert(sizeof(struct nvrm_class_desc) == 24, "nvrm_class_desc: size");
_Static_assert(_Alignof(struct nvrm_class_desc) == 4, "nvrm_class_desc: alignment");
_Static_assert(offsetof(struct nvrm_class_desc, hclass) == 0, "nvrm_class_desc.hclass");
_Static_assert(offsetof(struct nvrm_class_desc, param_size) == 4, "nvrm_class_desc.param_size");
_Static_assert(offsetof(struct nvrm_class_desc, fd_off) == 8, "nvrm_class_desc.fd_off");
_Static_assert(offsetof(struct nvrm_class_desc, flags) == 12, "nvrm_class_desc.flags");
_Static_assert(offsetof(struct nvrm_class_desc, fd_if_off) == 16, "nvrm_class_desc.fd_if_off");
_Static_assert(offsetof(struct nvrm_class_desc, fd_if_val) == 20, "nvrm_class_desc.fd_if_val");

struct nvrm_ctrl_desc {
	__u32 cmd;
	__u32 first;
	__u32 count;
	__u32 flags;
	__u32 fd_off;
};
_Static_assert(sizeof(struct nvrm_ctrl_desc) == 20, "nvrm_ctrl_desc: size");
_Static_assert(_Alignof(struct nvrm_ctrl_desc) == 4, "nvrm_ctrl_desc: alignment");
_Static_assert(offsetof(struct nvrm_ctrl_desc, cmd) == 0, "nvrm_ctrl_desc.cmd");
_Static_assert(offsetof(struct nvrm_ctrl_desc, first) == 4, "nvrm_ctrl_desc.first");
_Static_assert(offsetof(struct nvrm_ctrl_desc, count) == 8, "nvrm_ctrl_desc.count");
_Static_assert(offsetof(struct nvrm_ctrl_desc, flags) == 12, "nvrm_ctrl_desc.flags");
_Static_assert(offsetof(struct nvrm_ctrl_desc, fd_off) == 16, "nvrm_ctrl_desc.fd_off");

struct nvrm_nested_row {
	__u32 ptr_off;
	__u32 len_kind;
	__u32 len_off;
	__u32 elem;
};
_Static_assert(sizeof(struct nvrm_nested_row) == 16, "nvrm_nested_row: size");
_Static_assert(_Alignof(struct nvrm_nested_row) == 4, "nvrm_nested_row: alignment");
_Static_assert(offsetof(struct nvrm_nested_row, ptr_off) == 0, "nvrm_nested_row.ptr_off");
_Static_assert(offsetof(struct nvrm_nested_row, len_kind) == 4, "nvrm_nested_row.len_kind");
_Static_assert(offsetof(struct nvrm_nested_row, len_off) == 8, "nvrm_nested_row.len_off");
_Static_assert(offsetof(struct nvrm_nested_row, elem) == 12, "nvrm_nested_row.elem");

#endif /* _NVRM_WIRE_H_ */
