#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Silas Müller <github@silasmueller.de>
# SPDX-FileCopyrightText: 2026 Universität Stuttgart, IKR
# One (driver version, GPU) pair, measured.
#
#   scripts/abi-verify.sh [--with-display] [--skip-matrix]
#   scripts/abi-verify.sh table     regenerate the table in docs/abi-versions.md
#
# WHY THIS EXISTS. crates/nvrm-sys carries a measured LAYOUT for every driver
# version in abi.toml, and the compiler checks every offset in it. That is a
# statement about structs. It is not a statement that the boundary WORKS on
# that driver, and the two are not the same claim: a layout can be right while
# a control this tree never sent before is refused.
#
# So "supported" in docs/abi-versions.md is a measured PAIR, and this is what
# measures one. It writes matrix/abi-verify-<driver>-<gpu>.json, and
# `abi-verify.sh table` builds the doc's matrix out of those files -- so the
# table cannot name a pair nobody ran.
#
# WHAT A RUN NEEDS, and it is less than it used to be:
#   - the driver installed and running on the host;
#   - vendor/open-gpu-kernel-modules at that version, because the catalogue
#     resolves signatures against those headers;
#   - a rig (the gpu gate brings its own VM up).
# It does NOT need a rebuilt guest image: the guest's NVIDIA userspace is
# staged from the host at rig-up. It does not need a rebuilt guest module
# either, for 595/610/615 -- measured 2026-09-14, the generated header is
# byte-identical across those three; 580 differs, by the seven NVA083
# virtual-display defines that driver has no class for.
set -uo pipefail
LEA_ROOT=${LEA_ROOT:-$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd -P)}
# shellcheck source=scripts/lib/rig.sh
source "$LEA_ROOT/scripts/lib/rig.sh"
lea_cd_root

usage() { lea_usage_from_header; exit "${1:-0}"; }

DOC=docs/abi-versions.md
BEGIN='<!-- BEGIN generated by scripts/abi-verify.sh table -->'
END='<!-- END generated by scripts/abi-verify.sh table -->'

# ---------------------------------------------------------------------------
# table -- the doc's verification matrix, out of the result files
# ---------------------------------------------------------------------------
do_table() {
    [[ -f $DOC ]] || { error "no $DOC"; return 1; }
    local block
    block=$(python3 - "$LEA_ROOT" <<'PY'
import glob, json, os, sys
root = sys.argv[1]
rows = []
for p in sorted(glob.glob(os.path.join(root, "matrix", "abi-verify-*.json"))):
    with open(p) as f:
        r = json.load(f)
    stages = r.get("stages", {})
    verdict = "pass" if stages and all(v == "pass" for v in stages.values()) else "partial"
    if any(v == "fail" for v in stages.values()):
        verdict = "FAIL"
    ran = ", ".join(k for k, v in sorted(stages.items()) if v == "pass") or "nothing"
    rows.append((r.get("driver", "?"), r.get("arch", "?"), r.get("gpu", "?"),
                 r.get("date", "?"), verdict, ran))
if not rows:
    print("No pair has been measured yet. `scripts/abi-verify.sh` writes one\n"
          "result file per run and this table is built from those files, so an\n"
          "empty table means exactly what it says.")
else:
    print("| driver | architecture | GPU | measured | verdict | stages that passed |")
    print("|---|---|---|---|---|---|")
    for r in sorted(rows):
        print("| %s | %s | %s | %s | **%s** | %s |" % r)
PY
) || return 1
    python3 - "$DOC" "$BEGIN" "$END" "$block" <<'PY'
import sys
path, begin, end, block = sys.argv[1:5]
text = open(path).read()
b, e = text.find(begin), text.find(end)
if b < 0 or e < 0:
    sys.exit(f"{path} has no generated region ({begin})")
open(path, "w").write(text[:b] + begin + "\n" + block + "\n" + text[e:])
print(f"abi-verify: {path} updated")
PY
}

# ---------------------------------------------------------------------------
# a run
# ---------------------------------------------------------------------------
WITH_DISPLAY=0
SKIP_MATRIX=0
case "${1:-run}" in
    table) do_table; exit $? ;;
    run) shift 2>/dev/null || true ;;
    -h|--help) usage 0 ;;
esac
while [[ $# -gt 0 ]]; do
    case $1 in
        --with-display) WITH_DISPLAY=1; shift ;;
        --skip-matrix)  SKIP_MATRIX=1; shift ;;
        -h|--help) usage 0 ;;
        *) error "unknown argument: $1"; usage 2 ;;
    esac
done

driver=$(lea_driver_version)
[[ -n $driver ]] || { error "no NVIDIA driver running -- nothing to measure"; exit 1; }
if ! lea_driver_supported "$driver"; then
    error "driver $driver has no measured layout.
Supported: $(lea_supported_drivers | tr '\n' ' ')
Adding it:  ./scripts/build.sh vendor-abi $driver && cargo xtask abi"
    exit 1
fi
export LEA_DRIVER="$driver"

vend=$(git -C "$LEA_ROOT/vendor/open-gpu-kernel-modules" describe --tags --exact-match 2>/dev/null || echo none)
if [[ $vend != "$driver" ]]; then
    error "vendor/open-gpu-kernel-modules is at $vend and the running driver is $driver.
The catalogue resolves every signature against those headers, so a trace taken
now would be resolved against the wrong structs. Re-fetch first:
     LEA_DRIVER=$driver ./scripts/build.sh vendor"
    exit 1
fi

gpu=$(lea_matrix_gpu_field 'Product Name' 2>/dev/null || echo unknown)
slug=$(tr -c 'A-Za-z0-9' '-' <<<"$gpu" | tr -s '-' | sed 's/^-//;s/-$//')
out=$LEA_ROOT/matrix/abi-verify-$driver-$slug.json
mkdir -p "$LEA_ROOT/matrix"

lea_head "abi-verify  driver $driver  gpu $gpu"

declare -A RESULT=()
stage() {
    local name=$1; shift
    echo
    echo "== $name =="
    if "$@"; then RESULT[$name]=pass; else RESULT[$name]=fail; fi
    echo "-- $name: ${RESULT[$name]}"
}

# The GPU-free band first: it is cheap, and a red one makes every measurement
# after it a measurement of a broken tree.
stage check   ./scripts/test.sh check
stage gpu     ./scripts/test.sh gpu
[[ $WITH_DISPLAY -eq 1 ]] && stage display ./scripts/test.sh display
if [[ $SKIP_MATRIX -eq 0 ]]; then
    stage matrix-native ./scripts/ioctl-matrix.sh all
    stage matrix-guest  ./scripts/ioctl-matrix.sh guest
    stage matrix-verify ./scripts/ioctl-matrix.sh verify
fi

# The two numbers that say what the boundary looked like on this driver. Both
# are derived, both are cheap, and both are what a later reader wants when the
# question is "did the surface move".
tbl=$LEA_VM_DIR/abi-verify-tables.bin
mkdir -p "$(dirname "$tbl")" 2>/dev/null
checksum=unknown
if cargo run --quiet --all-features --bin nvrm-genhdr -- --abi "$driver" --dump-tables "$tbl" >/dev/null 2>&1; then
    checksum=$(python3 -c "import struct,sys;print('0x%08x'%struct.unpack_from('<I',open(sys.argv[1],'rb').read(),12)[0])" "$tbl")
fi

python3 - "$out" "$driver" "$gpu" "$checksum" "${!RESULT[@]}" -- "${RESULT[@]}" <<'PY'
import json, subprocess, sys, time, os
out, driver, gpu, checksum = sys.argv[1:5]
rest = sys.argv[5:]
sep = rest.index("--")
stages = dict(zip(rest[:sep], rest[sep + 1:]))

def sh(*cmd):
    try:
        return subprocess.run(cmd, capture_output=True, text=True).stdout.strip()
    except OSError:
        return ""

arch = sh("nvidia-smi", "--query-gpu=compute_cap", "--format=csv,noheader")
json.dump({
    "driver": driver,
    "gpu": gpu,
    "arch": arch or "unknown",
    "compute_cap": arch or "unknown",
    "kernel": os.uname().release,
    "date": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    "commit": sh("git", "rev-parse", "--short", "HEAD"),
    "tree_modified": sh("git", "status", "--porcelain") != "",
    "table_checksum": checksum,
    "stages": stages,
}, open(out, "w"), indent=2, sort_keys=True)
print(f"abi-verify: wrote {out}")
PY

echo
lea_head "abi-verify  $driver on $gpu"
for k in "${!RESULT[@]}"; do printf '  %-14s %s\n' "$k" "${RESULT[$k]}"; done
echo
echo "Fill the doc's table with:  ./scripts/abi-verify.sh table"
for v in "${RESULT[@]}"; do [[ $v == pass ]] || exit 1; done
exit 0
